### ISSUE TITLE
Update: [Nodejs_Security_Cheat_Sheet.md]

### ISSUE THREAD

**Issue by onepseudoxy** [OWASP/CheatSheetSeries#1001]
## What is missing or needs to be updated?
[csruf](https://www.npmjs.com/package/csurf) is deprecad

## How should this be resolved?
Customize [csrf](https://www.npmjs.com/package/csrf) for your needs

**Comment by bogdanoniga** [comment]
It is the case for [escape-html](https://github.com/component/escape-html) and [node-esapi](https://github.com/ESAPI/node-esapi) recommended libraries which are not maintained for years already.

**Comment by mackowski** [comment]
Issue with csruf was fixed in https://github.com/OWASP/CheatSheetSeries/pull/1008/files 
[escape-html](https://github.com/component/escape-html) and [node-esapi](https://github.com/ESAPI/node-esapi) are not deprecated or vulnerable. If there is a good alternative, please create a PR - we would love to review it!
