### ISSUE TITLE
CS XSS Prevention update rule 6 JS/Node lib(s)

### ISSUE THREAD

**Issue by rdela** [OWASP/CheatSheetSeries#101]
- What update/refactoring do you want to perform? 

Update JS/Node lib(s) on [Cross Site Scripting Prevention rule 6](https://github.com/OWASP/CheatSheetSeries/blob/113183c9d162a28ba41ad776b280806ec269bc95/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md#rule-6---sanitize-html-markup-with-a-library-designed-for-the-job).

Cross Site Scripting Prevention rule 6 links to [ecto/bleach](https://github.com/ecto/bleach) under "Other libraries that provide HTML Sanitization include: [...] JavaScript/Node.js Bleach" (Line 344).

The current (5 year-old) version, `bleach@0.3.0`, contains 1 moderate severity vulnerability according to https://npmjs.com/advisories/47

> ## Overview
> All versions of the bleach package are vulnerable to a regular expression denial of service attack when certain types of input are passed into the sanitize function.
> 
> ## Remediation
> The bleach package is not currently maintained, and has not seen an update since 2014.
> 
> To mitigate this issue, it is necessary to use an alternative module that is actively maintained and provides similar functionality. 

The advisory then links to a fairly unhelpful [search for "html sanitizer" on npmjs.com](https://www.npmjs.com/search?q=html%20sanitizer&page=1&ranking=optimal).

There is an open issue from 2016 at https://github.com/ecto/bleach/issues/12.

My cursory research into currently maintained libraries yielded two options:

1. [cure53/DOMPurify](https://github.com/cure53/DOMPurify), a DOM-only library that requires [JSDOM](https://github.com/jsdom/jsdom) on Node.js
2. [punkave/sanitize-html](https://github.com/punkave/sanitize-html), a Node.js-only library that depends on [htmlparser2](https://github.com/fb55/htmlparser2)

If OWASP contributors find both libraries adequate and satisfactory, my suggestion for the revision would be to split "JavaScript/Node.js Bleach" (Line 344) into two lines/list items like so:

- [JavaScript (DOM-only, requires JSDOM for Node.js)](https://github.com/cure53/DOMPurify)
- [Node.js (depends on htmlparser2)](https://github.com/punkave/sanitize-html)

If desired, I am willing to open a PR for the above suggested revision or whatever contributors advise. Thoughts?

**Comment by jmanico** [comment]
👍🏼👍🏼 Excellent find here. Thank you!

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by righettod** [comment]
Thank you very much for your proposal that is totally right. Please, go ahead with your PR and ping us if you need help 😃

**Comment by rdela** [comment]
Linked to PR #103 XSS CS Update

**Comment by mackowski** [comment]
One more time thank you for your contribution 👍

**Comment by jmanico** [comment]
Train your Developers on Secure Coding

View this email in your browser (https://mailchi.mp/875ff264e773/manicode-security-june-2019?e=7d9c298ae5)


** Manicode Security
------------------------------------------------------------


** Secure Coding Education
June 2019 Update
------------------------------------------------------------
Secure Coding Classes
Thank you for being a customer, partner or associate of Manicode Security.

Manicode Security is now offering over a dozen different application security classes delivered by four different instructors.
* Ron Perris is now teaching classes in React, Node.js, Express and JavaScript secure coding.
* Jimmy Mesta is teaching classes in Kubernetes, AWS, GPC, Cloud Security and DevOps security.
* Dr. Philppe De Ryck is teaching classes in Advanced Web Security.
* And Jim Manico is teaching classes in a wide variety of Web and API Security topics.
* Classes are also available in Mobile Secure Coding and Penetration Testing.

You can download our full catalog here https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=f5e5c7f0ff&e=7d9c298ae5

Please drop us a line at info@manicode.com (mailto:info@manicode.com?subject=Info-June-2019) if you have any questions about our application security classes!
Manicode Security is Partnered with Bit Discovery

The one singular thing literally every information security professional agrees upon is that all organizations must have an inventory of all their internet-connected assets. This includes all websites, name servers, mail servers, IoT devices, blogs, and so on. Of course, an inventory is also required by most every information security standard. And the reason is simple, you cannot secure what you don’t know that you own. Period. Creating a complete asset inventory has proven exceptionally technically challenging, time-consuming, and labor intensive. This has to change. Bit Discovery’s mission, having invested the last several years creating a fantastic product, is making sure every organization has a complete asset inventory. Instantly created. Automatically updated.

Please visit https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=a6b3d01345&e=7d9c298ae5 for more information or email contact@bitdiscovery.com (mailto:contact@bitdiscovery.com)  to schedule a live demo to create an asset inventory for your organization and receive a free trial account.

============================================================

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://manicode.us19.list-manage.com/about?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=7d9c298ae5&c=b62483214f)     unsubscribe from this list (https://manicode.us19.list-manage.com/unsubscribe?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=7d9c298ae5&c=b62483214f)     update subscription preferences (https://manicode.us19.list-manage.com/profile?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=7d9c298ae5)
Manicode Security . PO Box 676 . Anahola, HI 96703-0676 . USA

Email Marketing Powered by Mailchimp
http://www.mailchimp.com/monkey-rewards/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=monkey_rewards&aid=3b283d304057d06aaba6dc8fb&afl=1
