### ISSUE TITLE
Update: Password Storage Cheatsheet

### ISSUE THREAD

**Issue by oddcb** [OWASP/CheatSheetSeries#1043]
## What is missing or needs to be updated?
PBKDF2 iterations.

Looking into the past commits to the cheat sheet it seems the current ones were sourced from: 

https://twitter.com/sc00bzt/status/1322164349738262528

These recommendations were updated again this December: 

> Parallel PBKDF2
> PPBKDF2-SHA512: cost 2 (Based on RTX 4090 as "1.5 GPUs")
> PPBKDF2-SHA256: cost 5 (Based on RTX 4090 as "1.5 GPUs")
> PPBKDF2-SHA1: cost 10 (Based on RTX 4090 as "1.5 GPUs")
> 
> PBKDF2 (worst)
> PBKDF2-HMAC-SHA512: 210,000 iterations (Based on RTX 4090 as "1.5 GPUs")
> PBKDF2-HMAC-SHA256: 600,000 iterations (Based on RTX 4090 as "1.5 GPUs")
> PBKDF2-HMAC-SHA1: 1,300,000 iterations (Based on RTX 4090 as "1.5 GPUs")
> 

https://infosec.exchange/@sc00bz/109599362314030488

See also: https://tobtu.com/minimum-password-settings/

## How should this be resolved?

Update cheat sheet with new values. I'd also add a reference to source for anyone wondering where these numbers come from.

**Comment by jmanico** [comment]
This is super useful. Would you care to PR? If not I can.

**Comment by Moksh45** [comment]
Could you please provide me with additional information regarding this issue?

**Comment by kwwall** [comment]
@Moksh45 Specifically what additional information met regarding this issue are you seeking? If you are referring to specific comments made on these 2 PRs, then please reference a link to the specific comment and when asking about it, please also @-mention the individual who made the comment. Otherwise, we have to look for it and try to guess what you are specifically asking about. Thanks!

**Comment by Moksh45** [comment]
@kwwall The issue I had regarding these two pull requests has been resolved. 

Thank You.

**Comment by mackowski** [comment]
I see that this is already addressed. I am closing the issue
