### ISSUE TITLE
Update: Secrets Management Cheat Sheet

### ISSUE THREAD

**Issue by willpowerforever** [OWASP/CheatSheetSeries#1124]
## What is missing or needs to be updated?
When people need to remove hardcoded secrets from the github, the current cheat sheet in section 9.2 Remediate suggests to remove the secrets from commit history. See the quoted sentence below:
_"Deletion: Secrets revoked/rotated must be removed from the exposed system immediately, including secrets discovered in code or logs. Secrets in code should have commit history for the exposure squashed to before the introduction of the secret, and logs must have a process for removing the secret while maintaining log integrity."_

The problem on removing secrets from commit history is it will change the commit Id which is generated based on the content. The commit id change will make everywhere where have the references to the original commit id become invalid.

## How should this be resolved?
Suggest to provide a recommendation considering about the potential impact and make it practical and acceptable to engineers and also mention about the potential issue to remove the secrets from the commit history

@rewtd, please help review this proposal.

**Comment by kwwall** [comment]
My $.02: Most see this whole "commit history cleanup" as a part of a defense-in-depth approach. I see it as:

1.  Not worth the effort.
2. It is generally ineffective because you don't know if someone has cloned or forked the repo and they have a local copy of the commit history somewhere.
3.  Possibly in violation of company policy related to Audit. In rare cases, it may be a violation of mandatory regulatory policy.
4. It has bad optics. It could be viewed as a cover-up attempt.

The primary means of addressing this is just remove the hard-coded plaintext secret from Git (or other code version control) repos and then change the secret to some new random value. That has to be mandatory and should generally be sufficient. Removing it from commit history may save someone from embarrassment and thus from some reputational damage, but I generally feel that it's usually going to be better to just be transparent. If you try to remove it and miss a case where someone cloned it to their laptop and they bring it up later, the general public will think that you are attempting a cover-up rather than following recommended security practice.

YMMV.

**Comment by rewtd** [comment]
I would agree that re-writing the commit history doesn't actually add any security and because it breaks things like deep links used in other places and could potentially break other things it may actually be an anti-pattern. I'll propose a change based on that.

**Comment by aaronjdftf95** [comment]
Thank You
