### ISSUE TITLE
Cheat sheet update/refactor proposal: Password Storage Cheat Sheet

### ISSUE THREAD

**Issue by peter279k** [OWASP/CheatSheetSeries#118]
- What update/refactoring do you want to perform? 

According to [this cheat sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Password_Storage_Cheat_Sheet.md#argon2-usage-proposal-in-php), the Argon2 will be supported since `php-7.2`.

However, the `PASSWORD_ARGON2ID` will be supported since `php-7.3`.

I think this related algorithm should be mentioned in the `PHP password storage` section.

We can also add some sample codes and this algorithm introduction.

Reference: [password-hash](https://www.php.net/manual/en/function.password-hash.php)

**Comment by righettod** [comment]
Hi, according to this
https://wiki.php.net/rfc/argon2_password_hash_enhancements I think that we
can move directly to PASSWORD_ARGON2ID for the proposal and update the
existing samples because the call syntax seems to be identical (perhaps
conf value should be adapted). In all case, thank you for your proposal.

**Comment by mackowski** [comment]
This was deleted from CS in #258
