### ISSUE TITLE
Update: Deserialization_Cheat_Sheet.html#python

### ISSUE THREAD

**Issue by suraj-sec** [OWASP/CheatSheetSeries#1203]
## What is missing or needs to be updated?

In the Python's BlackBox Review section, there is not much info on how to find if the website is performing serialization in the backend. This can be little be improved by adding following suggestions in this section. 

## How should this be resolved?

Current - If the traffic data contains the symbol dot . at the end, it's very likely that the data was sent in serialization.
Proposed - If the traffic data contains the symbol dot . at the end, it's very likely that the data was sent in serialization. It will be only true if the data is not being encoded using Base64 or Hexadecimal schemas. If the data is being encoded, then the best way to check if the serialization is likely happening or not is to look for if any parameter value is starting with gASV (if the data is Base64 encoded) or c28004c29526000000000000 (if it is encoded in hexadecimal).

Ref - (https://macrosec.tech/index.php/2021/06/29/exploiting-insecuredeserialization-bugs-found-in-the-wild-python-pickles.)- The signature for a python serialized object is gASV. That’s how you can identify an encoded payload. If it is in hexadecimal, it would be c28004c29526000000000000.

**Comment by szh** [comment]
Can someone more familiar with Python please evaluate this?

**Comment by Bornunique911** [comment]
The proposed addition provides valuable information and context for identifying serialization in Python, including considerations for data encoding and specific markers associated with Python serialization formats; it enhances the original suggestion and can be beneficial for those reviewing websites for potential security vulnerabilities related to deserialization, taking into account that data may also be encoded using Base64 or Hexadecimal schemas, which is a crucial addition because data can be serialized and then encoded before transmission, making checking for the dot alone insufficient to confirm serialization; furthermore, the proposed addition mentions specific markers like "gASV" for Base64 encoding and "c28004c29526000000000000" for hexadecimal encoding, which are accurate for Python's serialization formats, with "gASV" being associated with Pickle serialization, and the hexadecimal string appearing to be a marker for a specific type of object in Python serialization, and it also references a source (https://macrosec.tech/index.php/2021/06/29/exploiting-insecuredeserialization-bugs-found-in-the-wild-python-pickles) to provide further context and credibility to the information.

**Comment by jmanico** [comment]
Looking forward to a PR for this, thank you!

**Comment by mackowski** [comment]
@Bornunique911 @suraj-sec do you want to create PR for this?

**Comment by Bornunique911** [comment]
I think so, yes, if @suraj-sec  agrees to create a PR for this. Actually, I just commented to further evaluate @suraj-sec's proposition in addition to the Deserialization CheatSheet, responding to @szh's comment to assess the difference between the current and proposed versions, especially for those familiar with Python.

**Comment by mackowski** [comment]
@suraj-sec do you want to create a PR for this?

**Comment by suraj-sec** [comment]
Hi @mackowski, apologies for late reply. I will create a PR for this.

**Comment by mackowski** [comment]
Awesome, thank you!

**Comment by suraj-sec** [comment]
Hi @mackowski, 

I have created a PR. Please have a look and let me know if any changes are required. I haven't included Hexadecimal schema since I am unable to reproduce the string mentioned on my end. I may be not trying it correctly but if someone is able to do that, please let me know that too. Thank you :)
