### ISSUE TITLE
XSS CS - Rule 2: confusion about name attribute

### ISSUE THREAD

**Issue by zer0uno** [OWASP/CheatSheetSeries#133]
The docs says:

> Rule #2 is for putting untrusted data into typical attribute values like width, name, value, etc. 

but after it says:

> Aggressive HTML Entity Encoding (rule #2), Only place untrusted data into a whitelist of safe attributes (listed below), Strictly validate unsafe attributes such as background, id and name.

So what about name attribute? Is it a safe attribute or not? Does the Rule 2 apply to it?

**Comment by righettod** [comment]
Hello, 
Thank you for your question.
Which cheat sheet you are refering to?
Thank in advance.

**Comment by zer0uno** [comment]
This one: https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md

**Comment by righettod** [comment]
OK, I have spot the point. Thank you 😃 

This [section](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md#xss-prevention-rules-summary) do not mention the attribute `name` as safe for untrusted HTML inclusion.

It's strange because the first sentence mention the attribute `width` but it is included into the safe list.

It's also strange that the attribute `value` is considered as safe for untrusted HTML inclusion.

I think we should:
* Remove the `width` from the sentence `Rule #2 is for putting untrusted data into typical attribute values like width, name, value, etc.`
* Validate with a POC that the attribute `name`  is not safe for untrusted HTML inclusion.
* Validate that the attribute `value` is safe for untrusted HTML inclusion.

@ThunderSon @mackowski @jmanico What do you think?

**Comment by ThunderSon** [comment]
I believe that `name` isn't an issue as a XSS attack, unless one can escape from it and inject other attributes. There totally is an issue with the CS, it was even asked on [StackOverflow](https://stackoverflow.com/questions/31526679/html-attributes-escaping)
I'll try and see if I can squeeze in a fix on this one.

Thank you for pointing the issue out 😄

**Comment by righettod** [comment]
OK so it's the same thing for the attribute `value`.

**Comment by mackowski** [comment]
@ThunderSon can we assign this issue to you? :)

**Comment by righettod** [comment]
So if I resume, the attributes `name` and `value` and `width` seems to be safe for untrusted HTML inclusion.

I have made a test to check:

```html
<html>

<head>
    <script>
        function upd() {
            var elt = document.querySelector("input");
            elt.setAttribute("name", "<img src='1' onerror='console.log(1)'>");
            elt.setAttribute("width", "<img src='1' onerror='console.log(2)'>");
	    elt.setAttribute("value", "<img src='1' onerror='console.log(3)'>");
        }
    </script>
</head>

<body onload="upd()">
    <input id="test" name="test" width="100" value="XXX" />
</body>

</html>
```

Execution result on Chrome (last version) using different content:

**Test with HTML with JS event**

![01](https://user-images.githubusercontent.com/1573775/59999311-f6e97580-9661-11e9-85fc-183d3feeedc7.png)

![02](https://user-images.githubusercontent.com/1573775/59999318-fa7cfc80-9661-11e9-952b-c9ab082fa560.png)

**Test with JS**

`</script>` was not added because it's break the parsing. 

![03](https://user-images.githubusercontent.com/1573775/59999324-010b7400-9662-11e9-8029-d06d0432de32.png)

![04](https://user-images.githubusercontent.com/1573775/59999339-07015500-9662-11e9-86c9-1aac40f4efb2.png)

**Test with a sample HTML tag**

![05](https://user-images.githubusercontent.com/1573775/59999365-1385ad80-9662-11e9-8456-be8deb49f72c.png)

**Comment by ThunderSon** [comment]
I'd love to see if the reporter would love to handle it.
@zer0uno Would you like to handle this issue? 😄

**Comment by zer0uno** [comment]
@ThunderSon Yeah, I'd love it! If you could give me some tips on what to next after what @righettod did I would appreciate it very much.

**Comment by righettod** [comment]
We can either do more tests and update the CS based on current test results...
@ThunderSon @mackowski What do you think?

**Comment by ThunderSon** [comment]
@zer0uno you'd mainly need to validate your points. What fields are actually safe? Which are not? Follow on dom's steps. Once that done, send a PR, we'll review and validate if there is anything missing. Just go forward with it. If you need anything while working on your tests, you can email us, or use this issue 😄

**Comment by mackowski** [comment]
@zer0uno do you need any help from us?

**Comment by zer0uno** [comment]
@mackowski Sorry for the delay, it was a tough period. I expect to process the issue by the end of August.

**Comment by mackowski** [comment]
No worries! Thanks for the update and let us know if you will need anything from us :-)

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by jmanico** [comment]
You can extract a list of safe attributes from the DomPurify projects which is a HTML sanitizer. It's the best research out there. https://github.com/cure53/DOMPurify

**Comment by jmanico** [comment]
Here is the exact list of safe attributes, it's the best list out there from one of the top XSS defense projects on the planet. https://github.com/cure53/DOMPurify/blob/main/src/attrs.js

**Comment by mackowski** [comment]
@jmanico do you want to update this CS or I should do this?

**Comment by jmanico** [comment]
Please.... I need some git learning first...

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by mackowski** [comment]
Sure I assigned issue to myself and I will make the changes in coming days.

**Comment by jmanico** [comment]
Thank you so very much. I'll get to git soon. I appreciate your help on this one!

**Comment by mackowski** [comment]
This will be adressed in #517
