### ISSUE TITLE
Update: Adding new language(s) translation(s)

### ISSUE THREAD

**Issue by PolVilniusTech** [OWASP/CheatSheetSeries#1410]
Provided content only in the single language.
 

Storage does not contain or accept translations from individuals, and even when this could be true, then in what form?
i.e. *.po files, or so.

Create simple folder and encourage numerous members from "OWASP Chapters" (World-Wide) [owasp.org](https://owasp.org/chapters/) participate and translate this content.

Adding minor organisational and international spice should be enough.

**Comment by szh** [comment]
Hi @PolVilniusTech,
I think having cheat sheets in multiple languages would be of great benefit. However, I'm not familiar with what methods are available for this. Can you fill us in on what other projects use for I18N?

**Comment by PolVilniusTech** [comment]
My opinion.
Best way for this project: simply use of "Content Negotiation" HTTP Option, i.e. request of "Accept-Language: fr; q=1.0, en; q=0.5" could suggest to grab French Language and when according the standard that language not Available, then move into default English option as it now You have (currently). Simple Web Content Management System could do.
Previous option more suited for Apps - Documentation, when this repository | depository are good place for.

**Comment by mackowski** [comment]
The problem with translation if that cheatsheets are "live" project, we do not have versions of it that can be translated (like for example top 10 that is released max ones a year). We would need to have translations for all supported languages for every PR. That means every 2-3 times a week. 
Frankly it is hard to get volunteers that will keep cheatsheets up to date in one language. That is great idea but it is not doable by us.

**Comment by ataseren** [comment]
Hello there, I have a suggestion about the translations. Currently, I'm translating ASVS to Turkish and the translation mechanism is easier for that project since there are versions of the standard and they are being updated in long periods. For this project, however, most of the cheat sheets are updated frequently and it makes impossible to apply such versioning.

My suggestion is using a versioning system for languages other than English. Each translated cheat sheet may have a date tag on them with a warning says that latest version is the English one. This is not the perfect solution but I think it is better than not having the cheat sheets in any other language.

To not cause any inconvenience, translated versions may only be stored in GitHub repository. In this way, there won't be any need for implementing a solution such as i18n. Also, PRs can be reviewed periodically to decrease the workload of verifying them.

Asking OWASP Chapters could be very useful because people from the chapters can be assigned to the translations of a language. But, such assignment may not be needed at all if there are (and I think there are) volunteers to translate them.

What do you think?
