### ISSUE TITLE
Auto-Assign Milestones and Projects

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#143]
**Purpose of the issue:**
Auto-assign the milestone and the project to the issues and PRs on creation.

The following article has some details for crafting custom URLs:
https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters

https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository

**Comment by righettod** [comment]
I have tried but **milestone** and **projects** cannot be added as properties of the template of issue/pr, you can only use them as query parameter.

The issue is that i do not control the url used when user click on the menu to select the kind of issue based on the issue template created:

![Capture](https://user-images.githubusercontent.com/1573775/60075436-97ed3480-9725-11e9-8d76-d2339f6429c1.png)

So, the only way to use this automation is to create 2 links that contributor must use for open an issue. It's not the expected way of using the UI of GH and it will create a duplicate with the existing template+menu as well as confuse the user.

For me, until these properties can be added to the template, it is not usable as is...

**Comment by ThunderSon** [comment]
I will be focusing on more urgent matters, especially as we are no longer using the project/milestones functionality for now (will be later on used when everything is in place properly).

**Comment by vuolter** [comment]
I really don't think this was "done".

**Comment by rayraspberry** [comment]
this doesn't seem to have been resolved yet.
