### ISSUE TITLE
Shortlinks for easier references to cheatsheet documents

### ISSUE THREAD

**Issue by tghosth** [OWASP/CheatSheetSeries#145]
hi folks,

If I want to put a reference to an OWASP cheatsheet in a document, the new GitHub links are a little long. Would it be worth creating shortlinks for them?

OWASP actually has this functionality through GSuite at http://sl.owasp.org. You can see more info from there. It looks like anyone with an OWASP account can create a shortlink there. It currently uses HTTP rather than HTTPS but for now I have raised that with the OWASP service desk as an issue.

For now, I have created:
http://sl.owasp.org/passwordstorage

@righettod should also have access to edit that link

**Comment by mackowski** [comment]
I like it! 
@tghosth Do you want to create it for existing cheatsheets? 
It will be also good to update README to explain how to do this for new CSs, the problem is a lot of contributors does not have OWASP account but in that case someone from core team can do it.

**Comment by mackowski** [comment]
@righettod @ThunderSon what do you think about it?

**Comment by tghosth** [comment]
> Do you want to create it for existing cheatsheets?

Let's wait and check that the others approve and also see if we can get the links shortlinks transitioned to HTTPS

**Comment by righettod** [comment]
Good point indeed, we have the issue #25 pending (we are waiting a decision from the foundation before to officially release it but we are ready since more than 2 months) to publish a web site with the shortest and stable link to every CS as well as indexes (better UI and navigation and dynamically generated from MD files).

I'm not against short links at all but there are 2 points that I want to highlight:
1. We (the core team) have already a huge amount of work to create/manage/maintain the CS thus I want to prevent us to have an extra task to maintains a list of shortened links.
2. I have seen many people on twitter raging against short links for security reason so I want to prevent any potential drama.

To be honest, I prefer that the point #25 be closed but as I'm bored to wait the ACK (I do not see any move forward) and I do no want to block you, you can add a link to the CS to point to the web site that is already published instead of the MD file.

**CS direct link example:** https://owasp.github.io/CheatSheetSeries/cheatsheets/Attack_Surface_Analysis_Cheat_Sheet.html

**Site home:** https://owasp.github.io/CheatSheetSeries

**Comment by ThunderSon** [comment]
I'd debate the need for the shortened links. @righettod Why is it that almost all the major projects have their own website/extension, and this project has been set on the back burner? I doubt the rest took any response or whatever, or simply ignored it. Let's push one last time with the board before using the website. It's been more than a month since that has been discussed.

**Comment by righettod** [comment]
> Why is it that almost all the major projects have their own website/extension, and this project has been set on the back burner?

When I have asked to the foundation (Matt Tesauro precisely) where I can store the web site generated, He answer to me to use the GH pages feature of the repo, so, I have followed the foundation response.

**Comment by righettod** [comment]
In addition, I have added information/question on the `owasp-ux` slack channel regarding a pending solution to tackle the issue on domain used (github instead of owasp) because it's mainly this point that seems to cause drama regarding SEO....

**Comment by tghosth** [comment]
Closed for now as per https://github.com/OWASP/CheatSheetSeries/issues/25#issuecomment-509279481
