### ISSUE TITLE
Update: REST Security Cheat Sheet

### ISSUE THREAD

**Issue by JoostK** [OWASP/CheatSheetSeries#1508]
## What is missing or needs to be updated?

The following section 

https://github.com/OWASP/CheatSheetSeries/blame/9c67e3ac45e2bfacd96e5dc324757cfb80e9ec1d/cheatsheets/REST_Security_Cheat_Sheet.md#L101

mentions:

> Reject requests containing unexpected or missing content type headers with HTTP response status `406 Unacceptable` or `415 Unsupported Media Type`.

forgoing requests with `Content-Length: 0` where no content is present. When there is no content, there isn't a suitable `Content-Type` header that applies, but this section doesn't specify the exact requirements here.

The [coreruleset/coreruleset](https://github.com/coreruleset/coreruleset/blob/a6036b984405798f5accec6a1fc5caaa90de46ac/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L709-L727) repository implements a detection rule that does account for `Content-Length: 0` and exempts the request from requiring a `Content-Type` header, as would be expected.

## How should this be resolved?
I'd propose to at least clarify the requirements here, going as far as suggesting that `Content-Length: 0` should not require a `Content-Type` header at all.

**Comment by JoostK** [comment]
Thanks for the quick reply! Sure thing, I've opened #1510 with a proposal. Happy to adjust as requested.

**Comment by randomstuff** [comment]
> forgoing requests with Content-Length: 0 where no content is present. When there is no content, there isn't a suitable Content-Type header that applies, but this section doesn't specify the exact requirements here.

Or it it? Let's say, you can PUT a text/plain or URI list to your API in order to override some text or some list of URIs. Your API would expect the proper content-type and reject the request if the proper content type is not user **but** you might still want to use it with an empty file in some cases.

In other words, an empty `text/plain` is still a `text/plain` and an empty `text/uri-list` is still a `text/uri-list`.

**Comment by jmanico** [comment]
I get the feeling you are both right.

The approach taken by the OWASP Core Rule Set (CRS), which exempts requests with Content-Length: 0 from requiring a Content-Type header, is practical. It aligns with the principle that when no content exists, a Content-Type header is irrelevant. This is especially useful in cases where an empty body is legitimately used to indicate certain states in an API call, such as "no change" or a placeholder.

But the point raised by @randomstuff, mentioning that an empty text/plain or text/uri-list is still valid content, is also valid. The clarification should, therefore, not only exempt Content-Length: 0 from requiring a Content-Type but also allow for cases where an empty body with a specific Content-Type can still be valid depending on the API's requirements.

I dont think either is more secure than the other, this is just a good way to clarify the rules around Content-Type since it does have other security implications.

**Comment by JoostK** [comment]
I agree with all of the above and my intent was to word it accordinly, but I realise now my current wording is still unclear. How about:

> For requests with `Content-Length: 0` a `Content-type` header is not required.

or

> For requests with `Content-Length: 0` a `Content-type` header is not required, but may be included.

Not quite happy with either to be honest, open to suggestions.
