### ISSUE TITLE
Update: Recommend Input sanitization as supplementary defense

### ISSUE THREAD

**Issue by timurozkul** [OWASP/CheatSheetSeries#1541]
## What is missing or needs to be updated?

The current cheats do not recommend input sanitization:
https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html
https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html
https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html]

I agree that input sanitization is not a strong prevention method for a sophisticated attacker for preventing malicious input but it is still a valid way of preventing. All other recommendation on input validation require individual implementation making it high workload and more error prone vs implementing a sanitization library as middleware which is quick win. Sanitization libraries help fend off a degree of attacks (ie DOMPurify). Many organization use sanitization libraries if they follow the OWASP guide and remove the sanitization libraries I would guess that they all would be worst off.

## How should this be resolved?

OWASP should recommend input sanitization as supplementary defense instead of primary however it should still be recommended none the less.

**Comment by randomstuff** [comment]
It makes sense for HTML (and some XML-based languages) under very specific circumstances but in many cases you actually want to do proper escaping instead. However it *is* actually [recommended](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#html-sanitization) in this case:

> HTML Sanitization
>
> When users need to author HTML, developers may let users change the styling or structure of content inside a WYSIWYG editor. Output encoding in this case will prevent XSS, but it will break the intended functionality of the application. The styling will not be rendered. In these cases, HTML Sanitization should be used.
> 
> HTML Sanitization will strip dangerous HTML from a variable and return a safe string of HTML. <mark>OWASP recommends [DOMPurify](https://github.com/cure53/DOMPurify) for HTML Sanitization</mark>.

For other contexts (such as SQL), I don't believe it makes sense and is opening up a huge can of worms.

**Comment by mackowski** [comment]
I think that depending on the case and design input sanitization can be as good and input validation as an supplementary defense. 
My logic is: When I see something that should not be part of the valid user input e.g. the input is outside of my allowed-list values, I can either reject the input or sanitize it. In both cases security is similar. 

The problem with sanitization is that it is much harder to implement correctly, because you need to do the same job as for input validation but later you also need to filter out dangerous input. Filtering out dangerous input is very hard and we saw that in the past with all HTML sanitizers had some issues with that.

Other aspect is UX. I am not expert in this domain but from my experience it is preferred to reject the bad input and return error to the user or API rather than mutate the input in unpredicted (for a consumer point of view) way. But that is a design decision we will not made in this CS.

So going back to the example of 
> filtering out ; DROP TABLE from an input field for "favorite food" 
What we gained (from security point of view) when we filtered out ; DROP TABLE in comparison to just returning the error and rejecting the input?

Also do we have some good examples of sanitization, outside of HTML (and some XML-based languages), that are proved to be a good defence step?

**Comment by jmanico** [comment]
Yea, a section that mentions that input validation helps but is not a complete defense when you allow certain control characters, is acceptable to me.

**Comment by jmanico** [comment]
A Validate-And-Sanitize strategy is solid. You might have input that takes a LOT of characters that could be dangerous. So you validate as best you can and if its valid - still run that content through a sanitizer. If the content changes, consider rejecting the content.

**Comment by elarlang** [comment]
> OWASP should recommend input sanitization as supplementary defense instead of primary however it should still be recommended none the less.

Just please no, https://github.com/OWASP/ASVS/issues/2381#issuecomment-2482518561

**Comment by elarlang** [comment]
> And why is html sanitization an exception?

HTML sanitization works as an allow-list of safe tags and attributes, mostly for WYSIWYG content.

**Comment by mackowski** [comment]
Thanks @elarlang for jumping to the discussion.

Also the WAF example is not good because Azure WAF or Cloudflare WAF do not do sanitization. 

Azure WAF documentation https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/create-waf-policy-ag#configure-waf-rules-optional 

> When you create a WAF policy, by default it is in Detection mode. In Detection mode, WAF doesn't block any requests. Instead, the matching WAF rules are logged in the WAF logs. To see WAF in action, you can change the mode settings to Prevention. In Prevention mode, matching rules defined in the Microsoft Managed Rulesets you selected are blocked and/or logged in the WAF logs

Cloudflare WAF documentation  https://developers.cloudflare.com/waf/concepts/ 

> The two main roles of the Cloudflare WAF are the following:
> 
> Detection: Run incoming requests through one or more [traffic detections](https://developers.cloudflare.com/waf/detections/) to find malicious or potentially malicious activity. The scores from enabled detections are available in the [Security Analytics](https://developers.cloudflare.com/waf/analytics/security-analytics/) dashboard, where you can analyze your security posture and determine the most appropriate mitigation rules.
> 
> Mitigation: Blocks, challenges, or throttles requests through different mitigation features such as [custom rules](https://developers.cloudflare.com/waf/custom-rules/), [Managed Rules](https://developers.cloudflare.com/waf/managed-rules/), and [rate limiting rules](https://developers.cloudflare.com/waf/rate-limiting-rules/). Rules that mitigate traffic can include scores from traffic scans in their expressions to better address possibly malicious requests.

You can either only detect or block traffic with potential malicious input (in CF you can also show captcha or throttle traffic). They are not doing sanitization.

**Comment by elarlang** [comment]
It should be taken as slow-down and anti-automation against scanners and script kiddies. If every cheat sheet, every standard and everyone else here is saying it is a bad idea, then maybe there is a good reason for that?

**Comment by jmanico** [comment]
I think deny-list validation is just fine for intrusion detection and as a secondary defense.

But I do not think deny list should *replace* standard validation rules we see in ASVS and similar.
