### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by cgimenes** [OWASP/CheatSheetSeries#163]
Are you planning to translate this project to others languages soon?
I think the community would be glad to have this kind of content in their native language.
If yes, I could help you translate to brazilian portuguese.

**Comment by righettod** [comment]
Hello,

It not plan to translate the project in other languages. 

The reasons are the following:
- The content of the project is technical and moves often, so, we do not have the resources to track and maintain the expected quality level of several versions of a cheat sheet (we have 63 cheat sheets for the moments and this number will grow in coming months).
- In respect regarding the diversity of our community, we cannot set one language above/prior another. If we decide to translate the project, for example to Brazilian then, we need to do the same operation for Chinese, Arabic, Jewish, Spanish, Russian, French...So it will bring an amount of work that is not possible to handle and keep the expected quality level of the project.

We have decided to use the English because it's the common language in IT that almost every IT people can read/write.

I understand the some people are not comfortable with English but our decision has to objective to ensure the quality and the maintainability of the project on a long-term perspective.
