### ISSUE TITLE
Cheat sheet update/refactor proposal: CSRF update regarding Double Cookie submit

### ISSUE THREAD

**Issue by elarlang** [OWASP/CheatSheetSeries#195]
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#double-submit-cookie

In Cross-Site_Request_Forgery_Prevention_Cheat_Sheet "Double Cookie submit" section there are problems/two attack vectors descibed (a and b). Both could not be valid, if CSRF token cookie could use `__Host-` prefix. Then:
* it's not possible to (over)write this cookie from other subdomain
* it's not possible to use path priority
* it's not possible to read and/or (over)write this cookie from HTTP connection

**Comment by mackowski** [comment]
Interesting, I did not know about cookies prefixes. Looks good for me. 
Do you know which browsers support it? IMO this information is crucial :)

**Comment by mackowski** [comment]
Some references about this feature

 - https://tools.ietf.org/html/draft-west-cookie-prefixes-05
 - https://googlechrome.github.io/samples/cookie-prefixes/
 - https://scotthelme.co.uk/tough-cookies/ 
 - https://www.sjoerdlangkemper.nl/2017/02/09/cookie-prefixes/

**Comment by mackowski** [comment]
@elarlang there is PR #160 you should wait with this PR after that one will be merged (should be relatively soon)

**Comment by elarlang** [comment]
> Do you know which browsers support it? IMO this information is crucial :)

Found this overview:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Browser_compatibility

**Comment by mackowski** [comment]
Ok so IMO after #160 will be merged you can start working on this.

**Comment by pikeje** [comment]
PR has been opened for this change. https://github.com/OWASP/CheatSheetSeries/pull/196

**Comment by manideepkonakandla** [comment]
Hey @elarlang , I was planning to look into this topic when I got to know from a friend that this cookie prefix is used at one popular storage company (but I never got time to look into it. Thanks for getting this out)!!

I tested this out now and it seemed to be working fine on my firefox and chrome browsers but the same wiki you pointed out earlier says that this API is still not standardized [1] and I also see some browsers having no support for this [2]. We should add this warning and ask people to be cautious about these things if they are planning to use it. The current work around I mentioned (with encryption) works good since it does not depend on browser specific functionality (I just realized there is a gap with current explanation, I made a pull request to fix it [3]).

Please let me know if I understood anything wrong.

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives
[2] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Browser_compatibility
[3] https://github.com/OWASP/CheatSheetSeries/pull/203

**Comment by elarlang** [comment]
Hi, @manideepkonakandla. Yes, it's not in standard. The fact that cookie prefixes does not belong to standards need to be mentioned.

In practice I can not see problem here. If browsers for most of the audience (chrome, firefox, ...) are supporting this technology, it already makes sense to use it.

SameSite attribute has the same state - it belongs to same proposal, it's not in standard.

From history we can take HttpOnly attribute. If I remember correctly, it was proposed by MS IE in 2003 and got to standard 2011 (rfc6265).

**Comment by manideepkonakandla** [comment]
Agreed, Samesite is also added as defense in depth measure in the cheat sheet for the same reasons.

Feel free to do the changes as discussed. Its good to have these cookie prefixes mentioned in the cheat sheet.

**Comment by ThunderSon** [comment]
@elarlang Hello Elar! Could you possibly create a PR for this issue and tackle it? And do you think that the __Secure prefix might have any meaning/addition to the CS?

**Comment by elarlang** [comment]
Sorry for delay. With opening issue I didn't take in account that there is expected PR to solve it myself.

Now, when I try to do it - may it be that I don't have enough privileges to do git push origin CSS-195?
File with modifications (and changed extension to .txt) is attached. My text needs corrections to proper English anyway.
[Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md.txt](https://github.com/OWASP/CheatSheetSeries/files/3640122/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md.txt)

**Comment by elarlang** [comment]
@ThunderSon `__Secure-` prefix is useful when you need to use `Domain` attribute or `Path` with value different than `/`.

**Comment by ThunderSon** [comment]
Don't worry about it! Kindly follow the [contributing guide](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#how-to-contribute). Let me know if there anything I can help you with.
And thank you for your reply on the Secure prefix.
Once a PR is opened I'll review it and amend any issues in it 😄

**Comment by mackowski** [comment]
Done in #332
