### ISSUE TITLE
Add link to GitHub on cheatsheets to encourage contribution

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#201]
When you're viewing a cheatsheet on the https://cheatsheetseries.owasp.org website it isn't immediately obvious that the content is pulled from GitHub, or how you could contribute to the project on the cheatsheets themselves (although there is a note at the bottom of the homepage).

Making this more obvious in the sheets themselves will encourage people to contribute (or at least raise issues). For example, on the [Microsoft Docs](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback) they have a section at the bottom of each page to allow you to quickly create an issue related to that document. Something like that is probably a bit more complicated (and GitBook may not support it), but adding a link with something like "Contribute on GitHub" or "Improve this Cheat Sheet on GitHub" to the header/footer like on the [Mozilla](https://infosec.mozilla.org/guidelines/web_security) cheatsheets would provide people an easy way to suggest changes.

**Comment by righettod** [comment]
Thanks for the remark.

Indeed, I didn't found how to add a common header or footer to the generated site with GitBook.
One possible way will be to update all the HTML files post-generation but I prefer to avoid this kind of dirty action.

After to be fully honnest, we have many suggestion (issues) opened every month but not soo many people to handle them and I want to avoid to have a project with 500 issues opened because when you reach this state the project become very hard to manage and maintains...

However, you remark is valid and very interesting, I flag it as INTERNAL (used to mark issue regarding the management of the project itself) in order to add it to project TODO list if we find a way to achieve that.

**Comment by rbsec** [comment]
It looks like you should be able to add [custom links to the header](https://docs.gitbook.com/content-editing/customization#add-header-links), although some of that functionality seems to be limited to specific plans.

Fully agree that you don't want a huge influx of low quality issues or suggestions. I would expect that a link along the lines of "Contribute on GitHub" would have quality results than the Microsoft approach of just letting people create issues (because you'd hopefully get less issues and more PRs), but it really depends on who's using the cheatsheets.

I suppose anyone who's genuinely interested and wants to contribute will probably find this repo anyway.

**Comment by righettod** [comment]
I use the [Gitbook V1](https://docs.gitbook.com/v2-changes/important-differences#cli-toolchain) for the generation of the site. Unfortunately V2 do not propose generation toolchain anymore...

I will use the #200 to investigate another generation system. Since december 2018, the main focus has been made to have a first full version of the project and the site on GitHub as well as the associated processes.

**Comment by mackowski** [comment]
I like this idea. I think that it is worth investigation how we can do this.

**Comment by rbsec** [comment]
This has been implemented on the new site.
