### ISSUE TITLE
Cheat sheet update/refactor proposal: Input_Validation_Cheat_Sheet.md

### ISSUE THREAD

**Issue by erichgoldman** [OWASP/CheatSheetSeries#224]
1. What is missing or needs to be updated in the current iteration of the cheat sheet?

In the _Implementing input validation_ section, the links for [Apache Commons](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Input_Validation_Cheat_Sheet.md#implementing-input-validation) point to deprecated functions.

2. How do you intend to resolve this with an update/refactoring?

It looks like in the current/new validators for Apache Commons are part of [routines](https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/package-summary.html)

I think it is just necessary to point to this link, but this may require some other changes.

**Comment by mackowski** [comment]
Validator package is not deprecated. 

You should still use classes like Validator, ValidatorAction, ValidatorResult etc. to create a validator and use it as input validation in your app and this CS is about that.

Deprecated are only concrete validators like CreditCardValidator because indeed concrete implementations of common data types are implemented in routines package.

What we can add here is to mention that for some common data types developers can use standard functions from routines package. But in general these validators from routines can not be suitable for all usecases/applications and does not provide a full framework for robust input validation.

**Comment by mackowski** [comment]
@erichgoldman do you agree with my comments? Do you want to create PR to make it more clear.

**Comment by mackowski** [comment]
Ok since I did not get any response in 20 days I will close the issue for now. Feel free to re-open it if you will have any second thoughts or ideas.
