### ISSUE TITLE
Update: Review password storage CS

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#237]
The current password storage CS is quite long, and has quite a lot of content of questionable usefulness and relevant to a CS. Main proposed change are:

* Update guidance on salts (you shouldn't be generating these yourself, any proper password hashing function handles this for you).
* Remove section on keyed functions/HMAC (is there any reason why you'd use this over a decent hashing function? Seems a bit like trying to roll your own crypto).
* Add some discussion of the use of a pepper (static addition to all hashes/password that's not stored in DB).
* Remove most of the stuff about Argon2. At the moment there's a lot of stuff that doesn't fit in a CS, such as:
  * Discussion about which compiled library to use
  * Long Java example code (can be linked to)
  * Instructions on how to compile PHP with argon2 support
  * Long PHP example code (can be linked to)
* Add some warnings about bad things that you shouldn't do (custom crypto, MD5, etc)
* Maybe some guidance on how to store passwords on legacy apps where you have no decent hashing algorithms available?

Thoughts?

**Comment by mackowski** [comment]
Good points!
I think that we should rethink how we want to include example code in CS. Storing it separately in some directory and linking to it seems for me to be a good choice. 
We can also add some tips how to migrate/update hashing algorithm in a working application.

**Comment by ThunderSon** [comment]
Sounds good to me.
About argon2, its usage should be straight forward.
@righettod What do you think about the code directory in order to make CSs nicer to read? 😄

**Comment by righettod** [comment]
I have created it, at this period, to give actionable code to user but indeed it made the CS long and less easy to read so extracting the code part to a sample directory with a link is a very good idea. 

My idea was, at the origin, to achieve that a CS be directly usable by a dev team so sample code or algorithm or approach was important in a CS even if including directly them was the not the better idea that i had 😄.

You refactoring is really a good idea, i'm very happy to see that the core team move the project to a next level, you rocks guys 👍

**Comment by rbsec** [comment]
The code sample issue is certainly an interesting one - I quite the idea of storing them in a separate folder, but there's also other options like having language specific cheat sheets that include all the relevant samples for that language. There might also be other OWASP projects that replace the need for samples (for example, if there's an OWASP CSRF protection library in Java, do we really need code samples in our CSRF cheat sheet). That's a discussion for another issue though.

Where we've got good sample code we certainly don't want to just throw it away, of course. Some of it might be be needed as much any more though (for example, if PHP is shipping with Argon2 support out of the box, then instructions on how to build it from source are less necessary).

**Comment by righettod** [comment]
> Having language specific cheat sheets that include all the relevant samples for that language

One of the biggest challenge for this orientation for the CS project is to keep the samples up to date with the evolution of the target language/technology. 

The intial idea of the CS was to explains a security issue, why it is important to prevent it?, how to address it from a technology agnostic point of view (ex: algorithm or schema or approach)? and provide (when applicable) an example in a technology allowing the dev team to derivate it to his context. Even with this initial idea it was difficult to keep the collection of CS up to date (you can just see the amount of CS that need to be updated/refactored).

So, having language specific CS **is really a good idea** but you need to ensure to have the work capacity to handle the workload bring to keep them up to date with the target technology. Moreover, with the evolution of the different frameworks for a specific technology (example for java is Spring Boot, JSF, Struts....)

Staying up to date is a crucial aspect of the project because as many dev team / pentest team use it as reference then an issue in CS can lead to a bad implementation or a security issue...

For the rest i'm totally agree with you that reference can be added to dedicated OWASP projects or samples refactored to focus on a topic or be more easy to read 😃

**Comment by rbsec** [comment]
I've made an initial draft PR #258. At the moment is basically the proposed headings with some of the old content kept when relevant.

Is there anything major that's missing?

I'm in two minds about the the section on storing encrypted passwords, but there are some times when you do need to be able to obtain the clear text passwords (or do things like check individual characters), so I'd be really interested in any feedback around that.

**Comment by rbsec** [comment]
This has been merged.
