### ISSUE TITLE
Cheat sheet update/refactor proposal: XML_External_Entity_(XXE)_Prevention_Cheat_Sheet

### ISSUE THREAD

**Issue by jzheaux** [OWASP/CheatSheetSeries#26]
The CERT coding standard indicates [a no-op `EntityResolver` as a way to prevent XXE in Java](https://wiki.sei.cmu.edu/confluence/display/java/IDS17-J.+Prevent+XML+External+Entity+Attacks), but I don't see it anywhere on the [XXE Cheat Sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md).

I'd be happy to add a section describing its use.

**Comment by righettod** [comment]
Hello,

Thanks you for your proposal.

Indeed, it's an interesting add.

You can add it after this [section](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md#saxbuilder).

You can find the info regarding the setup of your contributor environment [here](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#how-to-setup-my-contributor-environment), it's important in order to ensure that your update of the MD file is compliant with the linter.

Do not hesitate to ask if you have any question/problem 😃

**Comment by righettod** [comment]
@jzheaux: Hello, all is OK?

**Comment by jzheaux** [comment]
@righettod Hey, thanks for checking in.

Yes, all is fine, this just slipped off my radar. I'll have a PR ready in the next couple of days.

**Comment by righettod** [comment]
Hi, thanks you very much for your feedback, take the time you need there no
stress at all.

**Comment by righettod** [comment]
Associated PR is merged. Thanks again for the contribution 👍
