### ISSUE TITLE
CheatSheet structure proposal: Organize Cheat Sheet examples into per language/framework folders

### ISSUE THREAD

**Issue by jadsalhani** [OWASP/CheatSheetSeries#262]
Security CheatSheets tend to grow very long ( >= 180 Lines), which is much larger than a developer is used to reading on his screen (assuming he uses his linting tools properly 😄)

I suggest the CheatSheets be organized in a "folder-by-feature" kind of manner; this will allow contributors to group examples and references into subfolders and split the Cheat Sheet content into multiple `md` files inside the folder.

For example;
DotNet CheatSheet -> Every sub-section of `ASP NET MVC Guidance` can be separated into a standalone file (or even folder with related examples)

**Comment by mackowski** [comment]
Interesting idea. I agree that it is better to have smaller CS. 
@rbsec @ThunderSon maybe we should talk about this on our call?

**Comment by rbsec** [comment]
I certainly agree that there are some over-long cheat sheets, but I'm not sure about the approach of splitting them up like this. If you pull out every H2 from the DotNet CS (for example), you're going to end up with about 20 sheets, which sounds like real pain for anyone to actually use.

There needs to be a reasonable balance for the length, I'd say that we should aim for something like 10 pages maximum. Where they're bigger than that, we need to have a think about various ways to cut them down. There are quite a few different things we can do, but I think in order it should be:

* Removing fluff and unnecessary content/wording
* Removing duplicate content (for example, various places talk about MFA, which we can remove once we implement the MFA CS)
* Removing long code samples (as per other discussions)
* Splitting up the CS

I think there's a good point though about the language specific CS - they're trying to cover a huge amount of stuff, so are probably more prone to getting overly long. The DotNet one could certainly do with some cleanup though. From a quick skim through:

* A 50 line web.config sample showing how to set headers and a few other things
* Another 20 line web.config sample showing the same headers
* Three separate recommendations for HSTS (when we have a whole CS on this)
* Multiple sections talking about SQL injection

The top-10 style of the CS seems to cause a lot of duplication with the other parts of it, so maybe that needs to be looked at.

I think there are times where a CS can be split up, but it should generally be a last resort, otherwise we're going to end up with a huge number of different files to manage, and make it more difficult to actually use. A 20 page CS is a bit inconvenient, but I think that having to jump between ten 2 page CSs is much worse.

**Comment by mackowski** [comment]
@jadsalhani our team decided that we will try to remove fluff and unnecessary content/wording and to shorten code examples. We will also try to remove duplicate content across CS. 
For some CS we will consider to break it to smaller units but it will not be a rule.
In order to make navigation in large CS easier we will add table of contents at the beginning of the CSs.
