### ISSUE TITLE
Update: Input Validation CS - Regex Best Practices

### ISSUE THREAD

**Issue by aiacobelli2** [OWASP/CheatSheetSeries#301]
## What is missing or needs to be updated?
In the "Regular expressions" section, It would be nice to add in some part 2 concepts:

1- Regular expressions are slow and on the overall strategy must be used **after** all the others checks. 
2- When you are building regex to validate syntactics, be very careful with denial of service caused by backtracking. Check if your language is using NFA or DFA and, in case that is using NFA check that the regex is not vulnerable using projects like the following [ReDos Whitepaper](https://www.cs.bham.ac.uk/~hxt/research/redos_full.pdf)

**Comment by ThunderSon** [comment]
Doesn't sound bad at all. I am with giving a warning for users to note that regex shouldn't be the first thing to run to, and the risks it brings with it (reDoS). I doubt we should bring up much about NFA vs DFA in a CS. We can instead warn the regex creator on how to avoid ReDoS as it will be a better regular expression overall.

**Comment by aiacobelli2** [comment]
Agree about NFA vs DFA, but I can not think a way of teach how to check or avoid a potential ReDoS without mentioning Asiri Rathnayake1 and Hayo Thieleck research. 

There is a new implementation in node that is based on their work that check if a regex is dangerous or not by applying their concept: https://www.npmjs.com/package/safe-regex

**Comment by rbsec** [comment]
Agree with @ThunderSon that NFA/DFA (and that whitepaper) are too complicated for a cheat sheet -  it's hard enough to get people to read a few bullet points of best practices, let alone  40 page academic paper containing a lot of maths.

However we might be able to give some advice on common signs of bad regex (based on the [owasp](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) examples?), or libraries they can use to detect them.

Although it's non-trivial to identify if a regex is evil, maybe there are some rules we can give on how to create safe regex (like not having nested repetition)? Otherwise, the advice should probably focus on minimising the use of regex on user input, and how to sanitise the user input before passing it to a regex.

**Comment by aiacobelli2** [comment]
Yep! Agree on the part of thinking tips to create a safe regex including checking with a library or service.

**Comment by mackowski** [comment]
@aiacobelli2 I am reviewing older issues in the project. Are you interested in creating small PR for this issue?

**Comment by jmanico** [comment]
added a reference to RegExDOS 08a7de5d
