### ISSUE TITLE
Update: Input Validation CS - simple steps for developers

### ISSUE THREAD

**Issue by aiacobelli2** [OWASP/CheatSheetSeries#302]
## What is missing or needs to be updated?
I was reading the "Implementing input validation" section on this CS and I was wondering if was not better to add a step by step validation so a developer can read a implement an algorithm directly from our recomendation, for example related to simple inputs (not schemas or files): 

1- Define your applications encoding (utf-8, Ascii,etc ) and validate all inputs do not have adicional encodings. 
2- Verify no null or blank values are present.
3- Truncate all values to the max length defined. (for example using substring(0,N) java method for strings) 
4- Validate data types using native type conversion when possible. 
5- Apply Regular expressions to validate syntactical value. 

This is an over-simplified and not complete example, just wan to express the idea!

If you agree on the approach I can make a proper research for you to see!

**Comment by rbsec** [comment]
I like the idea of giving some simple steps for developers - as long as we can find a set that are (almost) universally appropriate.

I think the main thing I'd disagree with in the steps you've suggested would be truncating user input - this falls under the category of trying to fix input which is usually a bad idea. If you truncate overlong input, then either:

* The input was legitimate, and you now have incorrect (and probably invalid) input
* The input was malicious, and you have partially stored malicious input

In both cases it's better to just reject the input and require the user to submit something of a valid length. Also, if you're enforcing length limits on the client side with JS/HTML, and you receive input that's too long, you can just reject it because the user has clearly tried to bypass your restrictions.

**Comment by aiacobelli2** [comment]
Yep! I mention truncate as an example, I did not research the algorithm complexity of the length() or size() functions directly applied to a massive array of chars vs the complexity of first truncate and then check the length. 

I´ll be making a benchmark for 2 or 3 stacks to check if the performance is better on one scenario vs the other!

**Comment by mackowski** [comment]
This issue is no longer active, and we did not find what exactly need to be done here - I am closing this for now. Feel free to open it or create PR for review.
