### ISSUE TITLE
Update: Cryptographic_Storage_Cheat_Sheet

### ISSUE THREAD

**Issue by aiacobelli2** [OWASP/CheatSheetSeries#324]
Hi guys, how are you :D. I would like to add some opinions on this cheat-sheet that are confusing to read and can confuse non-expert developers.

## What is missing or needs to be updated?
**"Architectural Decision" section**  (I think that this section could confuse non-experienced developers)

- Mentioning RSA (and why not ECC) as the only asymmetric scheme (NOT only used for encryption, as mentioned on this cheat sheet) could confuse a reader that "storage encryption with asymmetric schemes is recommended". 
- Mentioning DH as key exchange scheme on this context is confusing too. 
- HMAC is not the only way to guaranty integrity, asymmetric schemes or symmetric authenticated modes are capable of this too. 
- I would divide the password hashing depending on the hardness, is useful if your threat model says that you need to be more resistant to ASIC's 
    -Argon2 or scrypt (CPU and RAM hard)
    - bcrypt or PBKDF2 (CPU hard only)

**Secure Cryptographic Storage Design**
Is confusing starting to read about digital certificates, that they never has been introduced to the audience and they are mainly used to secure information at transit, not at storage. 

**Rule - Use strong approved Authenticated Encryption**
- As a developer I would ask, approved by who? Who decide what type of encryption to use? And, are we talking about symmetric or asymmetric? 
- Related to the recommendation: "E.g. CCM or GCM are approved Authenticated Encryption modes based on AES algorithm (EAX missing)" This is not true, GCM or CCM are modes of operation that could be implemented on any block cipher by definition, not just related to AES construction.

**Rule - Use strong approved cryptographic algorithms**
You say: "Avoid hashing for password storage, instead use Argon2, PBKDF2, bcrypt or scrypt." You say on the first section that this functions are hash functions, and here you say they are not. On the other hand, we can discuss if Argon2 or the other constructions are not hash based functions :D.

**Rule - Use cryptographically secure pseudo random number generators (CSPRNG)**

When we recommend: "Ensure that random algorithms are seeded with sufficient entropy", this is quite complex to understand and actually achieve. If you speak about this topic you must speak about /dev/random vs /dev/urandom, entropy pool made by physical events or processors specific instructions (Ej. RDRAND) .

**Rule - Ensure that any secret key is protected from unauthorized access**

We could add on this topic the concept of key management and a small mention to the Kerckhoffs principle. Maybe mention the importance of HSM or HSM alike service to store this keys. 

**Rule - Define a key lifecycle**
Agree that crypto-periods are important and must be considered always. Maybe here we can mention something about strategies that need to be implemented in order to re-key all previously encrypted data-sets. 

**Rule - Store unencrypted keys away from the encrypted data**
Unencrypted keys should NEVER be stored unencrypted, here is when HSM or KEK schemes make sense!

Sorry for the long issue! I had a little time on my weekend and I would like to help as much as I could :D.

Tell me what you think!

**Comment by rbsec** [comment]
There's certainly a lot that could be updated in this CS - you're right that it's one of the more confusing ones (patly because crypto is hard). The "Rule" format is a bit weird as well compared to the others.

There are some sections that probably aren't really appropriate for a cheat sheet, for example:

> For secure random number generation, refer to NIST SP 800-90A. CTR-DRBG, HASH-DRBG or HMAC-DRBG are recommended. Refer to NIST SP800-22 A Statistical Test Suite for Random and Pseudorandom Number Generators for Cryptographic Applications, and the testing toolkit.

While this isn't incorrect, it's not useful advice for 99% of developers out there. They should just be using whatever CSPRNG function that their library/OS provides, and not worrying about the internals of how it works.

There's also a a lot about PCI DSS (about a third of the CS), which might seems a little heavy.

Regarding a few of your points:

* The password storage stuff needs cleaning up and removing - we have a CS dedicated to this, so it shouldn't be discussed here (just linked to).
* The certificate stuff is out of place - that belongs in the transport layer security cheat sheet.
* The comment about seeding random functions can probably be removed - if you're using a properly CSPRNG function then you shouldn't have to seed it yourself.
* While having a HSM is nice, realistically the vast majority of applications will not have one, so while it's worth mentioning, it's not very practical advice for most people. However there should be some discussion about ways you can store keys (encrypted keystores, OS provided secure storage, AWS KMS, etc). If you're not using one of those, then the use of a KEK is often just moving the unencrypted key to another folder/system, which doesn't really solve the problem.

@mackowski @ThunderSon do you think we're better trying to fix up some of the issues about in the existing CS? I'm hesitant to suggest a complete rewrite of this, because it's a very difficult area to try and write a CS for, but the current format could certainly do with some updates. Perhaps making incremental updates (based on the above) is a better approach here?

**Comment by pointhi** [comment]
I noticed the removal of scrypt in the Password Storage cheatsheet. On the other hand, scrypt is still mentioned in other cheat-sheets.

Was the removal an accident, or is there no reason to use scrypt in case Argon2 or PBKDF2 is not available? Either case, I would  suggest to add at least a mention of scrypt in Legacy Algorithms. Compared to the listed legacy algorithms, scrypt is designed for password hashing and not for speed like SHA.

**Comment by rbsec** [comment]
Regarding the inconsistency - this is because the cryptographic storage CS hasn't been updated yet (there's a PR to do so attached to this issue, but as you can see, it's not complete yet). Once it is, the entire password hashing section will be removed (as we have a dedicated CS for that), so there won't be any references to scrypt in this cheat sheet.

In terms of scrypt itself, there's nothing really wrong with the algorithm itself, but there's also not really much reason to use it. It didn't really achieve the objects of being GPU/FPGA/ASIC resistance (as demonstrated by the hardware used for the scrypt based cryptocurrencies), so unless you're very specific about how you tune it, it's not really much better than bcrypt.

On the other hand, if you have do a modern crypto library that supports scrypt (as it's not always available out of the box), and you know how to effectively tune it, then there's no real reason not to use Argon2id instead. It's the same kind of situation as TLSv1.1 - if you can support it then you're almost certainly able to support TLSv1.2, which is better.

It's certainly a better choice than any of the legacy algorithms discussed - but those are really only talked about for situations where you have no proper algorithms available, so have to make do with MD5/SHA.

We considered keeping it in as an alternative, but we didn't want to end up giving people too many options. 99% of people reading a cheat sheet like this are not really in a position to make a meaningful decision about Bcrypt vs Scrypt vs Argon2id - so giving people more options is often not really very useful. It's the same for the legacy algorithms - we could add a discussion of SHA vs Whirlpool vs RIPEMD - but it's not really useful to do so.

**Comment by jmanico** [comment]
I agree. I would suggest we keep bcrypt, scrypt and Argon2. I’m a little unhappy with several of the changes to this cheatsheet and plan to revamp it as soon as I can.

--
Jim Manico
@Manicode

**Comment by ThunderSon** [comment]
Closed by #325
