### ISSUE TITLE
Question: What's meaning of "Life is too short · AppSec is tough · Cheat!"

### ISSUE THREAD

**Issue by experdot** [OWASP/CheatSheetSeries#328]
Life is too short, and app security is tough 🤷. But I want to know how to understand "**Cheat!**".

**Comment by ThunderSon** [comment]
When you're facing a harsh exam, you bring on you a cheat sheet. Something that you can reference for formulas, for ways to do things, etc.
You're cheating your way through, instead of memorizing everything.

**Comment by rbsec** [comment]
You could also view it as rather than learning a full area (such all the details behind TLS configuration, vulnerabilities, the advantages and disadvantages of various ciphers, etc), you can "cheat" by just learning a much smaller set of good practices that contain most of what you need.

Developers are not security experts, and most of them never will be - the cheat sheets are intended to provide them with just enough knowledge that they can be more secure, without having to learn the entire background of a field.

At the end of the day, it's just a slogan - probably doesn't bear too much close examination.

**Comment by experdot** [comment]
@ThunderSon  @rbsec  
Thanks for your clear answer!
