### ISSUE TITLE
Cheat sheet update/refactor proposal: JWT for Java AES/GCM usage issue

### ISSUE THREAD

**Issue by RagingCactus** [OWASP/CheatSheetSeries#37]
[Section "Token information disclosure" in JSON_Web_Token_Cheat_Sheet_for_Java.md](https://github.com/OWASP/CheatSheetSeries/blob/c8330995864c14ab2124e23f8fd48c201f522f05/cheatsheets/JSON_Web_Token_Cheat_Sheet_for_Java.md#token-information-disclosure) describes an elaborate scheme to encrypt JWTs in order to hide their content from clients.

While I am not qualified to judge the overall quality of the cheat sheet regarding the JWT implementation, the usage of AES/GCM in this scheme demonstrates severe lack of understanding of its properties.

For the purpose of this description I will treat the JWT to be encrypted as an opaque, secret plaintext string `P`.
The cheat sheet proposes the following steps for encryption of the secret, given the secret key `K` and the plaintext `P` to be encrypted:
1. Initialize a AES/GCM cipher instance in encryption mode with the key `K` and a random nonce `N`
2. Obtain 32 random bytes (which I will call `A`) and add them as AAD to the AES/GCM cipher instance
3. Encrypt `P` using the AES/GCM cipher instance. This yields the ciphertext `C`.
4. Compute `SHA256(C)`
5. Store  `SHA256(C)`, `A` and `N` as a row in a database
6. Return `C` to send to the client

The proposed (authenticated) decryption then works as follows, given `C` and `K`:
1. Compute `SHA256(C)`
2. Use `SHA256(C)` to obtain `A` and `N` from the database
3. Initialize a AES/GCM cipher instance in decryption mode with key `K` and nonce `N`
4. Supply AAD data `A` to the cipher instance
5. Obtain `P` by decrypting `C` with the cipher instance and return it for further processing

Most of this protocol is completely pointless. The nonce `N` for AES/GCM must be unique, but is not required to be secret. It can safely be prepended to `C` and sent to the client. This removes the need to store the nonce in the database.
The AAD `A` that is used serves no purpose as well. It is random and is never used anywhere else but in the cipher. AES/GCM is an authenticated encryption mode. The additional data is optinal, and not required for authentication to be performed. The random AAD can safely be eliminated from the protocol.
This means that now no database is necessary for authenticated encryption/decryption. `SHA256(C)` was only used as a key to look up the other two values in the database, so this step can be dropped as well.

I suspect the other sections of the document may contain similar errors. Regrettably I am not knowledgeable enough about JWT to review it.

Please review the cheat sheet, or remove it if no volunteers can be found to do it. A lot of developers see OWASP as a trustworthy resource for security guidelines, so a flawed cheat sheet may cause more harm than good.

**Comment by righettod** [comment]
I think that it is important to clarify some points according to your post:

1. The migration to GitHub has for objective to allow more people to contribute in order to fix the issue in the project like potentially one that have raised.
2. Even if OWASP is a foundation working on security topics, it do not means that we never doing mistake, we are human (and doing this on our spare time) and the open source approach is used to allow eveyone wathever is origin (pro or not) to fix the potential error. 
3. OWASP contribution is not reversed to only so called "experts" on some topics, everyone can propose some technical proposal for an security issues and this can be used as foundation to enhance it.
4. The elements that you raised only highlight a paranoic approach usage of AES/GCM and do not proof that the ciphered value can be retrieved (that is the main goal of this section). Feel free to technically proof the inverse...
5. Instead of saying that you suspect that the cheat sheet contains many errors, proof them or better propose a pull request to fix the issue that you have identified.

**Comment by RagingCactus** [comment]
My goal was not to blame anyone, nor do I expect every document to be free of mistakes. I highly respect the volunteers to do this work in their spare time.

I looked at the document because I'm not an expert myself. I don't know all the ins and outs necessary to securely implement JWT and can't review the rest of the document with the appropriate scrutiny. I just noticed the unusual AES construction and from what I learned about encryption, unusual is not a desired property for solutions to standard problems.
While the proposed scheme does not seem to weaken the encryption, I disagree with the notion that not weakening the encryption is reason enough to pile more complexity on top.

You highlighted that you welcome community contributions. Why not use the issue tracker for readers to raise issues and requests for clarification? You can even stick "contributions welcome" labels on these to encourage people to look at potential issues.
Maybe we can get someone else to chime in on this!

**Comment by righettod** [comment]
Thanks vou very much for your feedback and the clarification about your intention.

In order to clarify the error, I have discussed with a crypto specialist about this point and indeed the NONCE and AAD are public so I will update the implementation proposed in this way to remove the DB and pass the NONCE and AAD along the ciphered value to the entity in charge of the deciphering.

Thanks for the proposal for the label I will update the labels and the readme in this way.

**Comment by RagingCactus** [comment]
Thanks for taking the time to clarify! Just a small addendum: 
You don't need any AAD in this case. If you don't set it GCM will still work and authenticate the payload.

**Comment by righettod** [comment]
You are welcome, the objective the have this project here is to discuss and handle the issue 😃 
Thanks you for your addendum, I will take it in account...

**Comment by righettod** [comment]
I have simplified the ciphering part using [Google Tink](https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md) API in order to allow users to use this API created and maintained by several crypto specialists.
I have also simplify others code samples of the ciphering section to enhance the readability of the cheat sheet.
