### ISSUE TITLE
Why does the password storage cheat sheet recommend a CSPRNG for salts?

### ISSUE THREAD

**Issue by nickform** [OWASP/CheatSheetSeries#373]
Is there a place where I can view discussions behind the wording in specific cheat sheets? I'm specifically interested in knowing the motivation behind this statement from the password storage cheat sheet:

> Generate a salt using a cryptographically secure function

Someone challenged me on why this was necessary and I couldn't answer. On further research, I found [this](https://crypto.stackexchange.com/a/35582) accepted and upvoted answer on crypto.stackexchange.com which states that since salts aren't secrets it is not necessary to use a cryptographically secure PRNG to generate them. Is there somewhere I can see discussion related to this specific statement from the cheat sheet like in a Wiki. I looked through PRs which touched the file but from a quick scan of the titles, they seem mostly about presentation rather than content.

Thanks in advance for your help and for these useful resources.

**Comment by jmanico** [comment]
A salt can be a counter; it just needs to be unique. It’s does not need to be random; good point.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by jmanico** [comment]
Even better; don’t do salting at all.

Use an algorithm that does salting for you like bcrypt scrypt argon2 and done, discussion over. Developers do not need to implement salting.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by rbsec** [comment]
Hi @nickform.

Glad that you've found the cheat sheets useful - and it's good that you're having these discussions. Always great to see people critically evaluating the recommendations they read rather than just blindly following them.

It's a good question, and as with most crypto related questions, the proper answer can get a bit complicated, but I'll have a stab at one.

**Short answer**

We give that recommendation because it's a simple, safe way to generate salts for people who don't want to dig deeper into the issue.

Also, if you're using a proper hashing algorithm, it will handle generating the salt for you automatically, so you don't even need to think about it.

**Longer answer**

You're correct that salts are not secret - which is the main reason why you would use a CSPRNG to generate them. The key thing about salts is that they should be _universally_ unique (i.e, unique across all applications and systems, not just within a system).

If you generate them with a non-secure PRNG, then you're increasing the chances that multiple users might end up with the same salt (for example, if your PRNG is particularly bad, or if it has a static seed or something like that). You're also adding a function that's known to be cryptographically unsafe into the middle of your authentication and hashing code. While you might be using it in a specific way that is safe, you're going to also have to add an explanation about why you're using a "known bad" function in crypto-related code, and to make sure that any other developers understand the specific reasons why you're doing this, and why it's safe in this particular instance. You're probably also going to have the same argument with anyone who carries out a code review.

Assuming your PRNG isn't really bad (or badly seeded), then there isn't really a _cryptographic_ issue with using it to generate salts. However, for the reasons stated above, it's likely to cause other issues (such as when another developer sees you using it and uses the same function somewhere where it does matter).

However, from a security perspective, we should really be asking the question from the other side. Assuming that you're going to randomly generate salts, _is there any reason why you should **not** use a CSPRNG?_ The main argument against them is usually performance, and unless you're generating a huge number of salts then this is very unlikely to be an issue.

Of course, you don't have to use randomly generated salts, you can use all lots of different methods to generate them. However, if you're going to implement something custom, you have to be careful that the salt are actually going to end up unique. Some other ways to create salts could be:

- The username (although other sites are likely to do the same thing)
- The email address (same)
- A sequential integer (unique for your site, but other sites may do the same)
- A UUID (may cause length issues with some algorithms, and may just be randomly generated depending on the type)

I'm sure that you can think of plenty of other (and probably much better) ways to generate a unique per-user salt - but any kind of custom algorithm you're writing here is just adding complexity, and as a general rule, doing custom crypto is a Bad Thing.

Ultimately the reason we recommend a CSPRNG is that it avoids having to have a long discussion about the pros and cons of the different approaches (such as those above), and it provides a simple recommendation that is easy for people to do correctly. It's by no means that only way to safely generate salts (just like there are other good hashing algorithms that we don't mention), but sometimes giving people more options can just confuse matters. One of the comments on that Stack Exchange thread sums it up nicely:

 > A CSPRNG is just the simplest way to generate a salt, not the only one.

Also, as mentioned above, this issue only comes up at all if you're not using a proper hashing algorithm in the first place.

The cheat sheets are primarily aimed at people who don't have a huge amount of knowledge in that area, so getting into deep technical discussions about things like this within the cheat sheet itself isn't really useful - it's just going to add too much complexity and noise. Unfortunately there isn't always a good page that we can point to as a reference for these things, and most of the discussions take place on the [OWASP Slack]( https://owasp-slack.herokuapp.com) (which you're very welcome to join), so they can't easily be linked to.

Sorry if this answer feels a bit scattered - but hopefully it's been helpful. Very happy to discuss any of this is more detail if you wish.

**Comment by nickform** [comment]
@jmanico @rbsec thanks for getting back to me so quickly with thoughtful responses. I agree that there are a lot more considerations here than a cheat sheet can or should really deal with. I particularly like @rbsec's points about the risk of introducing a non-secure PRNG in the middle of authentication code. It would be ideal if there was some way to review this kind of discussion around the wording in the documents for anyone else who has a similar question.

I'm closing this issue now - I don't want to clog up the project's issue tracking system for longer than necessary, especially since I now have a comprehensive answer to my question. Thanks again!

**Comment by rbsec** [comment]
@nickform we do try and give references where there are good ones to point to (although I'm sure there's scope to be better at this), but some of this topics are a quite hard to find anything authoritative for, and just pointing at random blog posts isn't ideal. On the plus side, if we do have someone else wondering about this then they mind find this issue.

Thanks
