### ISSUE TITLE
Query: CSRF cheat sheet

### ISSUE THREAD

**Issue by tghosth** [OWASP/CheatSheetSeries#425]
Hi @mackowski 

The reference to triple submit cookies was removed in this commit: https://github.com/OWASP/CheatSheetSeries/commit/50333c17f2c21ec9363427eeffb32ff384f0d9d4#diff-a60525267043449768bd6432eef357efL224

Was this a deliberate decision? ASVS [v13.2.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x21-V13-API.md#v132-restful-web-service-verification-requirements) specifically refers to this and references the cheat sheet.

Note that this relates to ASVS issue: https://github.com/OWASP/ASVS/issues/809

**Comment by mackowski** [comment]
Hey @tghosth we deleted it as the description of triple submit cookies was very poor and Cookie Prefixes solves the same problem but it is still good mitigation. We definitely can add it back but with good, short description with pros and cons of this solution.

**Comment by mackowski** [comment]
@tghosth Do you want to create PR for that?

**Comment by jmanico** [comment]
Double/Triple cookie submit is about adding sa ynchronize token to 
stateless requests to stop fraudulent transactions.

From https://www.sjoerdlangkemper.nl/2017/02/09/cookie-prefixes/: 
A|__Host-|-prefixed cookie is only accessible by the same domain it is 
set on. This means that a subdomain can no longer overwrite the cookie 
value.

So this makes the double/triple cookie submit pattern /stronger/ but 
does not replace it.

Are you saying we do not need triple submit (and double submit is 
enough) because of the __Host- header?

- Jim

**Comment by mackowski** [comment]
Exactly it seems that double submit is enough when used with __Host- cookie prefix. It was first noticed in this issue: https://github.com/OWASP/CheatSheetSeries/issues/195. 
But if ASVS link here and mention triple submit cookie we should add since it is still good protection especially if someone use ASVS to assess older application.

**Comment by elarlang** [comment]
I'm related with both issues:
- https://github.com/OWASP/CheatSheetSeries/issues/195 on the CheatSheetSeries side
- https://github.com/OWASP/ASVS/issues/809 on the ASVS side

Point for triple-submit-cookie (<https://media.blackhat.com/eu-13/briefings/Lundeen/bh-eu-13-deputies-still-confused-lundeen-wp.pdf>):

> There can only be exactly one cookie with the prefix in the request or request fails.

With `__Host-` prefix this condition is satisfied (like I wrote in #195), because:

- it's not possible to (over)write this cookie from other subdomain
- it's not possible to use path priority (usage of `__Host-` prefix requires `Path` attribute value to be `/` == it's not possible to write many cookies with the same name for different paths (but they all may match for request))
- it's not possible to read and/or (over)write this cookie from HTTP connection (usage of `__Host-` prefix requires `Secure` attribute to be set)

Some concerns:
- One question is - how much there is need to take in account Internet Explorer, because based on <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Browser_compatibility> it does not support `__Host-` prefix.
- Second question is - should CSRF cookie match for many subdomains `Domain=.example.com`? I can not see the reason, why it should, but of there is a reason, then `__Host-` prefix does not fit in that situation.

**Comment by tghosth** [comment]
Based on on @mackowski 's response and having had a quick search, my current feeling is that triple submit cookies are so rare/unknown that I don't think it is worth mentioning them for now. I will see if we can get them removed from ASVS.

**Comment by jmanico** [comment]
👍🏼👍🏼

--
Jim Manico
@Manicode

**Comment by ThunderSon** [comment]
@elarlang Thanks for the detailed answer. To answer your questions, the CS project shouldn't really go into extreme edge (no pun intended) cases. If their risk appetite goes to such lengths then they better be talking with a security team, as the issues discussed aren't common.
