### ISSUE TITLE
Update: Clarify guidance around security headers for REST APIs

### ISSUE THREAD

**Issue by dotnetnate** [OWASP/CheatSheetSeries#445]
## What is missing or needs to be updated?
The referenced cheat sheet requires that REST APIs return x-frame-options and set the values to deny. This is not meaningful or useful in the context of a REST API and seems to serve nothing more than to cause extra work and contention when having to explain this to security teams blindly reading vulnerability scan reports that are based off of OWASP documentation without understanding the context. The only possibly feasible manner in which this becomes relevant is if an API is returning HTML content for direct rendering in the browser. 

## How should this be resolved?
The statement to include x-frame-options header should be removed or make it optional, and only for APIs that return HTML, which a scanner should be able to detect via regex.

**Comment by rbsec** [comment]
This is an interesting area - thanks for raising it. I think that the [Security Headers](https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html#security-headers) section in that cheat sheet could do with a rewrite, because this is an question that I've run into a few times.

There are some security headers that are important and should be sent by almost every REST API (such as HSTS). Others like CSP or X-Frame-Options are less useful, although they may still have some benefits depending on exactly what the API returns (which isn't always known).

Not all client will support them (browsers support HSTS, but not many other clients will), but I still think there's some benefit to setting them unless you can guarantee which clients will be used to access the API.

My view would be that you should set the same security headers on an API endpoint as you would on a website (especially if it doesn't have a dedicated domain) - because these headers are something that should be there by default, and while they might not always provide a security benefit, they'll never make your security worse.

If you can guarantee that your clients will never support them, or that there are no circumstances where they would provide a security benefit (such as if your API will never return HTML, including future versions) then that would be reasonable grounds to decide to disable them - but I think that the justification should be that way round ("why should I disable this security feature", rather than "why should I enable it").

It also stops people/scanning tools complaining, and although that's not a good reason to do something, in the real world it can end up being a reasonable justification for it.

I'm not aware of many authoritative sources for this (although as usual there's some discussion on [Security Stack Exchange](https://security.stackexchange.com/questions/147554/security-headers-for-a-web-api)) - so it might be a nice one for us to provide some clear guidance on. There's also a [few](https://observatory.mozilla.org/faq/) different [places](https://infosec.mozilla.org/guidelines/web_security#content-security-policy) where Mozilla are recommending a CSP for API endpoints.

@ThunderSon @mackowski @jmanico what are your views on this?

**Comment by dotnetnate** [comment]
Thanks for taking it under consideration. I think there's a bit of a vicious cycle between the guidelines and the tools since the tools and pen test providers are kind of just saying "well, it says it in OWASP, so..." and as you said above, we have to do it to appease the tools even though it's largely, if not completely (afaik), meaningless in that context.

Others are definitely useful/valuable, but this one just seems to cause grief for little useful value.

**Comment by rbsec** [comment]
I don't like the reasoning of "a scanner flags it", and I'll absolutely jump on any pentester who uses that as their justification to report an issue - but especially in larger organisations it does carry some weight.

Let's say we're trying to write a policy for a organisation about X-Frame-Options. If we say "All web applications just have it as DENY, but REST API endpoints only need it if they return HTML", that opens up all kinds of questions and complexity, such as:

* What about API endpoints on the same domain as a web application? Does only the application have it or the whole domain?
* How do we determine if an API will ever return HTML?
* What about MIME sniffing? If it's not disabled, can we guarantee a user couldn't trigger it?
* What about the drag-and-drop clickjacking-style attacks? How can we tell if we're vulnerable to them?
* What if new functionality can return HTML? Do we need to review this every time the API changes?
* This logic is too complicated for a scanner, so how we check for compliance automatically? Do we just have a list of false positives that we ignore in the findings? Do we add a load of manual exclusions so the check doesn't run on known "safe" APIs?
* Do we have to document our reasoning for each API we don't include it, so that we can argue with the pentesters/auditors? Will we have to argue with someone about why we only get a B on SecurityHeaders?
* etc

Then you go through the same arguments for CSP, X-Content-Type-Options, Referrer-Policy, Feature-Policy, etc....

And once you've gone through all that, and you've decided that a few API endpoints don't need X-Frame-Options, what's the benefit? The only real one I can think of is saving a few bytes in the HTTP response headers, and if performance and bandwidth is that critical on your application, you should probably be listening to your internal security team, not a cheat sheet or scanner output.

---

On the other hand, you could just have a policy that says "Any HTTP(S) service must set X-Frame-Options to DENY", and you're done. It's simple and means that your environment is consistent, so you can easily do automated checks that all your servers have it set.

**Comment by rbsec** [comment]
I've made a PR #448 with an initial draft for some updates text - any comments or feedback is very welcome.

**Comment by mackowski** [comment]
This was solved in #448
