### ISSUE TITLE
Refresh XSS Prevention Cheat Sheet 

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#517]
It is clear that this CS needs refreshing after ~10 years. That does NOT mean that this CS is wrong or give bad advice - quite the opposite, this is very conservative and if you implement it you should be free from XSSes. But this CS in the current form does not make it simple because it does not leverage modern frameworks and browser features. Keep the spirit of the CS and I will leave current recommendations (including escaping forward slashes) in the “conservative” section because I know that there are applications that needs to implement it in this fashion.

Main points of the new XSS CS:  
* Use safe contextual-autoescaping templating libraries
   * If above is not possible implement escaping in contact of HTML, HTML Attributes, JavaScript, HTML URL Parameter, CSS … preferably using library designed to to the job (e.g. OWASP Java Encoder)
 * Implement CSP (nonce-based preferably)
 * Implement Trusted Types 
   * If this is not possible other DOM-based prevention rules
In general we have all the rules currently here but I want to enforce using modern, well-designed and tested solutions over custom made implementation. 

During refactoring address 3 other open issues for this CS: 
https://github.com/OWASP/CheatSheetSeries/issues/133
https://github.com/OWASP/CheatSheetSeries/issues/141 
https://github.com/OWASP/CheatSheetSeries/issues/95

See also comments from https://github.com/OWASP/CheatSheetSeries/issues/515 and https://github.com/OWASP/CheatSheetSeries/pull/516

**Comment by chris-morgan** [comment]
This has *reintroduced* the erroneous escaping of slash, which was removed in d7a6823db92af82da3f9538b23b03851d7556d78.

**Comment by kwwall** [comment]
@mackowski - I know this particular issue is closed and I may be biased, but I'd really like to see the XSS Prevention Cheat Sheet include something about the anti-patterns that the ESAPI team (and probably others) have see pop up time and time again. I run into these constantly, because despite AppSec people constantly pointing devs to the XSS Prevention Cheat Sheet, this practice continues.

II have documented this in our local ESAPI GitHub wiki page [XSS Defense: No Silver Bullets](https://github.com/ESAPI/esapi-java-legacy/wiki/XSS-Defense:-No-Silver-Bullets).

Perhaps we can incorporate part or all of this or similar content in the XSS Prevention Cheat Sheet where I feel it really belongs and were devs are more apt to see it.  Or at least put a temporary link to this somewhere referring to the ESAPI wiki page. Because this approach is very prevalent because it is simple; simple, but wrong. And we don't warn devs about this.

**Comment by colecornford** [comment]
Hey @kwwall I'd be stoked to have a yak sometime. I think that some guidance around footguns + references to ESAPI would be top notch. 

So some background, when I wrote the refresh I wanted to really focus on dev UX. I cut a lot of content that otherwise would have been good and I think the ESAPI stuff fell into that bucket. So here's my general thoughts about your linked article and why I had trouble including it.

CSP > I cut all guidance I had in the XSS P CS. We figured it belonged in the CSP CheatSheet so that people don't try to implement CSP badly in lieu of effective XSS prevention, had a plan to link to it. My personal experience mirrors your own https://www.colecornford.com/2021-may/ so I wasn't happy killing my darling as I do think a good CSP is worth its weight when combined w/ Trusted Types. But I think very few organisations ever reach that maturity level, and wanted to avoid mentioning it as it may mislead engineers into thinking it is effective.

Interceptor patterns > I really like what you've written, but I also think that I've tried hard in the XSS P to get engineers to focus on context first for each output encoding method. The last iteration of the cheatsheet incorporated most of your suggestions and what I found hard was making those technology agnostic and remaining simple for newly minted software engineers to understand.

Anyway, keen for a chat if you ever want to my email is on my profile. 🙇

**Comment by jmanico** [comment]
> @mackowski - I know this particular issue is closed and I may be biased, but I'd really like to see the XSS Prevention Cheat Sheet include something about the anti-patterns that the ESAPI team (and probably others) have see pop up time and time again. I run into these constantly, because despite AppSec people constantly pointing devs to the XSS Prevention Cheat Sheet, this practice continues.
> 
> II have documented this in our local ESAPI GitHub wiki page [XSS Defense: No Silver Bullets](https://github.com/ESAPI/esapi-java-legacy/wiki/XSS-Defense:-No-Silver-Bullets).
> 
> Perhaps we can incorporate part or all of this or similar content in the XSS Prevention Cheat Sheet where I feel it really belongs and were devs are more apt to see it. Or at least put a temporary link to this somewhere referring to the ESAPI wiki page. Because this approach is very prevalent because it is simple; simple, but wrong. And we don't warn devs about this.

Bring it on. Keep is concise *KEVIN* but we do take PR's and I support this direction.

**Comment by kwwall** [comment]
@jmanico wrote:
> Bring it on. Keep is concise KEVIN but we do take PR's and I support this direction.

I'll see what I can do, but being concise is not my forte. :-)

I'll start by creating a new issue which you can assign to me, and then create a PR, but the rest of you are going to to have to do your best impression of _Reader's Digest_ editors.

**Comment by kwwall** [comment]
@colecornford - I'll drop you an email about this once I create a GitHub issue for this. Then we can decide whether we want to continue discussing it via email or carry out any discussion on the new issue. The latter is probably better from a transparency perspective. But I'll provide you my phone and other instructions if you want to follow up that way as well.

**Comment by mackowski** [comment]
@kwwall sure, updating and refreshing XSS Prevention Cheat Sheet was not a simple task given the popularity, importance and history of this cheatsheet. We should keep improving it. XSS Defense: No Silver Bullets is perfect! 

You can create a new issue for it or just make a PR, depending on what do you prefer. We can also link to the ESAPI GitHub wiki page where needed.
