### ISSUE TITLE
Update: [Password Storage Cheat Sheet]

### ISSUE THREAD

**Issue by quiver** [OWASP/CheatSheetSeries#640]
## What is missing or needs to be updated?

> bcrypt has a maximum length input length of 72 characters for most implementations. To protect against this issue, a maximum password length of 64 characters should be enforced when using bcrypt.

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#input-limits

From this sentence, it's not clear where does the max length(64) come from.
My guess is  `8 = MAX_INPUT_LENGTH(72) - MAX_PASSWORD_LENGTH(64)` is reserved for the salt.

## How should this be resolved?

It would be great to explain why the max length of passwords is 64.

**Comment by mackowski** [comment]
Thanks @quiver!
@jmanico do you want to take that one?

**Comment by jmanico** [comment]
Thank you for your comment, I agree. Would you like to propose a PR or would you like me to take it on directly?

**Comment by quiver** [comment]
@jmanico @mackowski 

> Would you like to propose a PR or would you like me to take it on directly?

Let me make this clear.
Does "you" refer to @mackowski or @quiver (me) ?

If my understanding is correct(i.e. 8 characters are reserved for the salt), I can create a PR for that.

**Comment by jmanico** [comment]
I was referring to @quiver :)

**Comment by quiver** [comment]
@jmanico 

Created a PR #643

Can you review that?

**Comment by rbsec** [comment]
Hi @quiver,

I was involved in writing an earlier version of this cheat sheet.

The 64 character limit isn't actually related to the salt. There were a couple of reasons for giving a length lower than 72 characters (which should be the maximum):

* Depending on whether the strings are null terminated, you may lose one character there.
* Although a good implementation of bcrypt _should_ support 72 characters, there's various articles online that talk about bad implementations with lower limits. I'm not actually come across a modern implementation that does this (all the ones I've tested have allowed 72 chars), but I can't say for sure that there aren't any out there.
* The input limit for bcrypt is actually 72 _bytes_, not 72 _characters_. This means that if you include any non-ASCII characters in the input then a single "character" might end up being represented as multiple bytes. So it's not necessarily safe to just check that `length($input) <= 72`, because it depends exactly how `length()` works in your language.

Given these issues, 64 was decided on because it gives a reasonable safety buffer to avoid these issues, without making real difference to the strength of the password (because 64 chars is still ~420 bits of security).

You might still be able to cause issues with specifically crafted passwords (like a long password made entirely of emojii), but that will depend on the specific implementation, and you're unlikely to run into problems in real-world usage.

**Comment by quiver** [comment]
@rbsec 

Thank you for your explanation.

> bcrypt has a maximum length input length of 72 characters for most implementations. To protect against this issue, a maximum password length of 64 characters should be enforced when using bcrypt.

The issue is that the full bytes of the password might not be used for hashing.
The wording definitely needs to be improved.

There's a wide gap between the first and the second sentence.

**Comment by jmanico** [comment]
So @rbsec the 64 CHARACTER limit can be easily exceeded if the password contains many characters like emoji that take up multiple bytes. So it sounds like 64 char limit for bcrypt is not clear enough.

**Comment by rbsec** [comment]
@quiver I'd agree that those two sentences doesn't really follow on from each other. The [earlier version](https://github.com/OWASP/CheatSheetSeries/blob/009e81088527260ad2ac43f2e875ea3c3656dbe5/cheatsheets/Password_Storage_Cheat_Sheet.md#maximum-password-lengths) explained this is a bit more detail.

So for example, if you made a password that was:

```
😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁
```
That password is 32 characters long, but 128 bytes. If you're checking that passwords are no longer than 64 characters, then this password _might_ pass that check, but then end up being truncated to 72 bytes when you call the `bcrypt()` function on it.

It will depend on how you're checking the length of the string though - the `len()` function in Python3 would return 32, but PHP's `strlen()` would return 128, and so not be affected.

This is a tricky problem to solve from a UX perspective. On the user-facing side, you would normally have a message that refers to the maximum "length" or a maximum number of "characters" - but because a characters is not always the same as the byte, that doesn't work on the backend. If the user entered the password above and you return an error that it needs to be less than 64 characters they'll (rightly) be confused, because it is less than 64 characters. But then you can't really display a warning to the user that their password contains too many bytes, and they need to either shorten it or use characters that contain less bytes - they won't have any clue what you're talking about.

By setting a limit of 64 characters you avoid truncation in cases where a password contains a couple of multibyte characters, which is the most likely case. You can create passwords (like the one above) that _might_ avoid this check (depending on how the length of the string is calculated). But the only real impact then is that their password will be truncated to 72 bytes (18 characters) before it's hashed. While truncation like this isn't ideal, it's also not really exploitable (as you're still providing ~470 bits of security), whereas if you pre-hash the passwords, there are attacks against that (such as password shucking).

It's also worth bearing in mind that this isn't a bcrypt specific issue - it applies to any time you try and implement a length restriction (which you should be doing for any type of password hash to protect against DoS attacks).

---

You could write an entire book (or several) on the topic of password hashing. One of the key things that I tried to achieve when I was writing this CS was to try and provide a simple set of good (not perfect) practices that would be easy for developers to actually follow, rather than going into detailed explanations about all the intricacies of the topic. Apparently I failed in doing so - hopefully you'll have more success than I did.

Capping the length at 64 characters isn't perfect, but it's a simple thing for the developer to implement, easy for users to understand, and in the vast, vast majority of cases will work fine (because let's be honest, half the users are going to use Password123 anyway). In the few edge cases with like this one, it fails in a safe way (truncating the password to 72 bytes).

**Comment by jmanico** [comment]
I’m open to a PR to expand on this more. I am trying to make the cheatsheet lean and actionable, hence the very specific suggestions at the top. But if you want to bring some of the older text back in please consider a PR for us. :)

**Comment by mackowski** [comment]
Thank you @rbsec! 
I closed PR #643 as invalid. Please create new PR to address it.

**Comment by quiver** [comment]
Given that

- input length limitation is not specific to bcrypt
- long passwords can cause DoS
- prehashing passwords can cause another problem(e.g. password shucking)

how about making "Maximum Password Lengths" its own distinct section as before?

[The earlier version](https://github.com/OWASP/CheatSheetSeries/blob/009e81088527260ad2ac43f2e875ea3c3656dbe5/cheatsheets/Password_Storage_Cheat_Sheet.md#maximum-password-lengths) @rbsec mentioned is exactly like that. It's easy to follow the logic.

I didn't check every change so I don't know why the section was truncated that terse.

**Comment by quiver** [comment]
If I were to beef up the doc, it would be byte/(multi-byte) character(like emoji 🍣) difference.

**Comment by jmanico** [comment]
We already have requirements for:

8 char password min
Must support at least 64
No more than 128 for performance (max)

The problem is that bcrypt requires a much smaller max due to it’s 72 byte limit.

**Comment by quiver** [comment]
@jmanico 

> We already have requirements for:
> 
> 8 char password min
> Must support at least 64
> No more than 128 for performance (max)

Where are these requirements written?

> The problem is that bcrypt requires a much smaller max due to it’s 72 byte limit.

Hey, let's get back to the original discussion.

> From this sentence, it's not clear where does the max length(64) come from.

Everyone can understand the bcrypt's 72-byte limit.
I'm discussing about the magic number 64. 

For me, the section is too lean to understand.
You(= @jmanico ) also couldn't understand it only by reading the sentence.

If the OWASP cheat sheet is not intended to demystify technical details(it's Cheat Sheet) but to provide specific guidance, just close this issue.

I'm 100% sure readers do not need to understand the reasoning behind "8 char password min".

**Comment by jmanico** [comment]
Dear @quiver I agree 100% that the 64 character limit is problematic 
since the real bcrypt limit is 72 byes. Our explanation is lean and the 
limit is not always accurate.

I would like to avoid pre-hashing. I believe that mechanism is also 
problematic for a lot of reasons.

My suggest is that we fully remove bcrypt from the cheatsheet and 
suggest more modern password hashing algorithms since more modern 
choices are widely available.

- Jim

**Comment by jmanico** [comment]
Even better How about we just change 64 characters to 72 bytes? cc @quiver

**Comment by jmanico** [comment]
Does this PR meet your approval? https://github.com/OWASP/CheatSheetSeries/pull/665 cc @quiver

**Comment by quiver** [comment]
> Even better How about we just change 64 characters to 72 bytes? cc @quiver
> Does this PR meet your approval? #665 cc @quiver

+1

Thank you for your PR.

**Comment by mackowski** [comment]
Addressed in #665
