### ISSUE TITLE
Merge Key and Secrets

### ISSUE THREAD

**Issue by jmanico** [OWASP/CheatSheetSeries#763]
Merge the live Key Management Cheatsheet and the draft Secrets Management Cheatsheet

**Comment by commjoen** [comment]
Currently just joined together with @bendehaan , @dominikdesmit and want to give this a go. Instead of merging it, we suggest to first work on the draft for the SM CS . Can we pause this issue for a moment, and first work on finalizing the SM cheatsheet and then see what is still required for key-management ?

**Comment by commjoen** [comment]
Currenlty the SM cheatsheet references the KM CS as these are really 2 different things. the SM cheatsheet is really about broader practices, while the KM CS is more specific about technicalities regarding key management. Can we close this :) ?
