### ISSUE TITLE
CSP CS Avoid section update

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#93]
Following PR  #92, `Avoid CSP` section should be re-worded and changed to highlight how CSP can act as a firm second layer to protect against XSS attacks.

**Comment by righettod** [comment]
I propose a text, feel free to pick elements that go in your way:

*CSP can act as a second layer of defence in a way that a policy can result in a non-exploitability of an XSS vulnerability.  Indeed, depending on the policy defined, it can prevent an attacker to execute injected client-side code or send/receive data to/from another domain than the one on which the application is loaded.*

*Due to this blocking capacity, a CSP can be used to add a mitigation measure on a vulnerable application in which XSS flaws cannot be currently fixed for different kinds of reasons (time, knowledge...).*

*CSP can also be applied on a pure static site (no input used to generate content) in order, for example, to require the usage of the [Sub Resource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) feature to prevent flaws caused by the compromising of a CDN on which the site load content or prevent the site to execute Flash animation.*

*To resume, CSP can be used to transform the browser in a cage in which a XSS vulnerability can be present but cannot be exploited.*

**Comment by ThunderSon** [comment]
If you feel like opening a PR, go ahead! If not, I'll update this and inject it into the CS tonight.

**Comment by righettod** [comment]
I let's you inject the content in order to let you decide which part and where if fit the most 😃

**Comment by aussieklutz** [comment]
May be worth adding some recommendations about how to implement, as per Troy Hunt/ReportURI, to get notified of issues and build out rule sets.

**Comment by righettod** [comment]
We will add the proposed content and we will add later element from Troy Hunt via a dedicated ticket.

@ThunderSon You can inject the proposed content into the CSP CS ? Thank you very much in advance 😃

**Comment by ThunderSon** [comment]
Of course. This is in no way definitive. I am a currently a bit busy, which is why no additions have been made on this CS. Once I am available, a good chunk of updates will be coming its way. If you feel like you can improve the CS in any way, please open an issue with its corresponding PR 😄

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃
