### ISSUE TITLE
Cheat sheet update/refactor proposal: CSP CS Add Trusted Types

### ISSUE THREAD

**Issue by righettod** [OWASP/CheatSheetSeries#95]
**What update/refactoring do you want to perform?**

Add a section explaining how to apply a CSP policy that leverage the *Trusted Types* new feature.

According to this [post](https://developers.google.com/web/updates/2019/02/trusted-types#get-started), currently (may 2019) this feature is not ready for production usage: 

*We are working on providing more code examples, guides and documentation on how to migrate applications to Trusted Types. We feel this is the right moment for the web developer community to start experimenting with it.*

By the way, I have tested (may 2019)  the [demo page](https://wicg.github.io/trusted-types/demo/):
* All tests are green on the last version of Firefox (66.0.3) and Chrome (74.0.3729.131) and Opera (58.0.3135.132) on a WIN10 Pro.
* Tests n°4 and n°12 are red on Edge (44.17763.1.0) on a WIN10 Pro.
* Page do not load in IE11 (11.437.17763.0) with error `SCRIPT5009: 'Reflect' is undefined` and `SCRIPT5009: 'TrustedTypes' is undefined` on a WIN10 Pro.

:alarm_clock: Process this request only when Google will indicate that the *Trusted Types* will be ready for production

**Comment by koto** [comment]
Production-readiness should happen when we move out of Origin Trials into main Chrome (planned for Q4 this year). 

I fixed the demo (Edge does not support iframe.srcdoc, hence the breakage). I'll look into IE11 support in the polyfill, but I don't have high hopes, that browser is just too far behind. We do have full support in the polyfill for FF, Chrome, Edge and Safari though.

**Comment by ThunderSon** [comment]
@koto Thank you for the update! Do you think that a CS could be prepared prior to the release of the technology to the main release of Chrome which could be added to the list of CSs at release time?

**Comment by koto** [comment]
Sure thing. It all depends on how detailed you want the cs to be, as the
API will for sure change a little bit still. But we'll definitely know the
final shape in chrome at least a few weeks before that chrome reaches
stable channel. We're also working on some other TT projects that might be
useful to add to the cs. All announcements will be at
https://groups.google.com/forum/#!forum/trusted-types, my Twitter etc.

**Comment by jmanico** [comment]
Thank you very much for this effort!

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
Train your Developers on Secure Coding

View this email in your browser (https://mailchi.mp/875ff264e773/manicode-security-june-2019?e=b01eb889b3)


** Manicode Security
------------------------------------------------------------


** Secure Coding Education
June 2019 Update
------------------------------------------------------------
Secure Coding Classes
Thank you for being a customer, partner or associate of Manicode Security.

Manicode Security is now offering over a dozen different application security classes delivered by four different instructors.
* Ron Perris is now teaching classes in React, Node.js, Express and JavaScript secure coding.
* Jimmy Mesta is teaching classes in Kubernetes, AWS, GPC, Cloud Security and DevOps security.
* Dr. Philppe De Ryck is teaching classes in Advanced Web Security.
* And Jim Manico is teaching classes in a wide variety of Web and API Security topics.
* Classes are also available in Mobile Secure Coding and Penetration Testing.

You can download our full catalog here https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=f5e5c7f0ff&e=b01eb889b3

Please drop us a line at info@manicode.com (mailto:info@manicode.com?subject=Info-June-2019) if you have any questions about our application security classes!
Manicode Security is Partnered with Bit Discovery

The one singular thing literally every information security professional agrees upon is that all organizations must have an inventory of all their internet-connected assets. This includes all websites, name servers, mail servers, IoT devices, blogs, and so on. Of course, an inventory is also required by most every information security standard. And the reason is simple, you cannot secure what you don’t know that you own. Period. Creating a complete asset inventory has proven exceptionally technically challenging, time-consuming, and labor intensive. This has to change. Bit Discovery’s mission, having invested the last several years creating a fantastic product, is making sure every organization has a complete asset inventory. Instantly created. Automatically updated.

Please visit https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=a6b3d01345&e=b01eb889b3 for more information or email contact@bitdiscovery.com (mailto:contact@bitdiscovery.com)  to schedule a live demo to create an asset inventory for your organization and receive a free trial account.

============================================================

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://manicode.us19.list-manage.com/about?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=b01eb889b3&c=b62483214f)     unsubscribe from this list (https://manicode.us19.list-manage.com/unsubscribe?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=b01eb889b3&c=b62483214f)     update subscription preferences (https://manicode.us19.list-manage.com/profile?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=b01eb889b3)
Manicode Security . PO Box 676 . Anahola, HI 96703-0676 . USA

Email Marketing Powered by Mailchimp
http://www.mailchimp.com/monkey-rewards/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=monkey_rewards&aid=3b283d304057d06aaba6dc8fb&afl=1

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by jmanico** [comment]
Bumping @koto we would love your help, even one or two paragraphs explaining the basics of Trusted Types would help us a lot. To make it easier you are welcome to just add it as a comment and I'll take it from there. Whatever works to make it easy on you. :)

**Comment by koto** [comment]
Hey! I guess the best canonical place would be to simply mention that DOM-based XSS can be prevented by rewriting the application to use Trusted Types and linking to https://web.dev/trusted-types/. We mean to keep this article as a canonical starting point for developers, on top of the github repo (https://github.com/w3c/webappsec-trusted-types). Would that work, or do you need something more prescriptive?

**Comment by jmanico** [comment]
Perfect.... :)

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by mackowski** [comment]
I agree that we should just link to https://web.dev/trusted-types/ with a very short intro. I will make changes next week and ping you for review.

**Comment by koto** [comment]
We are working on a more prescriptive documentation (like a cookbook, or - a cheatsheet), the patterns we use for migrating to Trusted Types are still emerging. I'll keep y'all in the loop. @shhnjk is also working on it (focused on Chromium pages) - https://gist.github.com/shhnjk/a44b13dfdbd83c79bd1e2c1b08508f9d.
