### ISSUE TITLE
Update: Secrets Management Cheat Sheet

### ISSUE THREAD

**Issue by GeorgesBolssens-Toreon** [OWASP/CheatSheetSeries#968]
## What is missing or needs to be updated?

Go to https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_CheatSheet.html
Click one of the hyperlinks in the navigation
Expected result: Browser jumps to that section
Actual result: Nothing happens

Tested in Safari 15.5, Chrome 104, Firefox 103.0.2

## How should this be resolved?

I'm unaware of the CMS you are using. You are better fit to decide this.

**Comment by szh** [comment]
This appears to be the only cheat sheet that has it's own navigation links included in the Markdown, despite the fact that the CMS provides a sidebar with a table of contents.
I also noticed an oddity in how this cheat sheet is listed in the navigation: It has the "CheatSheat" and ".md" suffix which seems out of place. I don't see a place in the repo where this can be fixed so I'm assuming it's because it's also the only cheat sheet that ends with `CheatSheet.md` without an underscore in between the two words.

![Screen Shot 2022-08-31 at 4 11 28 PM](https://user-images.githubusercontent.com/546965/187772975-516fa71a-9f7c-45b5-9635-740dc3d7cb3d.png)

I'll make a PR to fix both inconsistencies.
